require("dns").setServers(["8.8.8.8", "8.8.4.4"]);
require("dotenv").config();

const mongoose = require("mongoose");
const Coach = require("../models/Coach");
const Academy = require("../models/Academy");

const coaches = [
  {
    slug: "rahul-dravid-cricket-bengaluru",
    name: "Rahul Dravid",
    avatar: "/images/coaches/rahul-dravid-cricket-bengaluru.svg",
    certifications: [
      { name: "BCCI Level 3 Coach", issuer: "BCCI", year: 2014 },
      { name: "ICC Level 2 Coach", issuer: "International Cricket Council", year: 2017 },
    ],
    experienceYears: 18,
    sportsCoached: ["cricket"],
    specialization: ["batting", "red-ball technique", "youth development"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 12.9789,
      lng: 77.5996,
    },
    contact: {
      phone: "+91 98 6012 9001",
      email: "coach.dravid@nationalcricketacademy.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.9, count: 184 },
    status: "published",
    bio: "Former India captain and head coach renowned for nurturing young talent and building resilient batting line-ups. Known as \"The Wall\" for his technically impeccable batting.",
    achievements: [
      "Coached India U-19 and India A teams to multiple series victories",
      "Led India to the 2024 ICC T20 World Cup semi-finals as head coach",
      "Received the Padma Shri award for contributions to cricket",
      "Scored 13,288 runs in Test cricket with 36 centuries",
    ],
  },
  {
    slug: "anil-kumble-spin-bengaluru",
    name: "Anil Kumble",
    avatar: "/images/coaches/anil-kumble-spin-bengaluru.svg",
    certifications: [
      { name: "BCCI Level 2 Coach", issuer: "BCCI", year: 2013 },
    ],
    experienceYears: 22,
    sportsCoached: ["cricket"],
    specialization: ["spin bowling", "match strategy", "mentorship"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 12.9789,
      lng: 77.5996,
    },
    contact: {
      phone: "+91 98 4500 1234",
      email: "coach.kumble@nationalcricketacademy.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.9, count: 142 },
    status: "published",
    bio: "India's highest wicket-taker in Test cricket who transitioned into coaching and sports administration. Expert in spin bowling craft and match-day strategy.",
    achievements: [
      "Took 619 Test wickets, the fourth-highest in world cricket history",
      "Former head coach of the Indian national cricket team",
      "Named ICC Cricketer of the Year in 1996",
      "Received the Padma Shri and Arjuna Award for cricket excellence",
    ],
  },
  {
    slug: "saina-nehwal-badminton-hyderabad",
    name: "Saina Nehwal",
    avatar: "/images/coaches/saina-nehwal-badminton-hyderabad.svg",
    certifications: [
      { name: "BWF Coach Education Level 2", issuer: "Badminton World Federation", year: 2018 },
    ],
    experienceYears: 9,
    sportsCoached: ["badminton"],
    specialization: ["singles", "footwork", "rally endurance"],
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "IN",
      lat: 17.4399,
      lng: 78.3569,
    },
    contact: {
      phone: "+91 99 4900 1850",
      email: "saina@pgbadminton.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.8, count: 211 },
    status: "published",
    bio: "One of India's most decorated badminton players, now coaching the next generation of singles specialists. Known for her aggressive playing style and mental toughness.",
    achievements: [
      "Won a bronze medal at the 2012 London Olympics in women's singles",
      "Claimed the 2015 All England Open Badminton Championships title",
      "First Indian to win the World Junior Badminton Championships",
      "Recipient of the Padma Shri and Rajiv Gandhi Khel Ratna awards",
    ],
  },
  {
    slug: "pankaj-advani-billiards-bengaluru",
    name: "Pankaj Advani",
    avatar: "/images/coaches/pankaj-advani-billiards-bengaluru.svg",
    certifications: [
      { name: "World Billiards Cert. Coach", issuer: "World Billiards & Snooker Federation", year: 2019 },
    ],
    experienceYears: 14,
    sportsCoached: ["billiards"],
    specialization: ["cue sports", "mental focus", "long-format endurance"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 12.9789,
      lng: 77.5996,
    },
    contact: {
      phone: "+91 98 4502 3456",
      email: "pankaj@chessgurukul.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.7, count: 78 },
    status: "published",
    bio: "India's most successful cue sport athlete, holding multiple world titles across billiards and snooker. Now mentors aspiring cue sport players with a focus on mental discipline.",
    achievements: [
      "Won over 20 world titles in billiards and snooker",
      "Recipient of the Padma Shri for contributions to cue sports",
      "Youngest Indian to win the World Billiards Championship",
      "Awarded the Rajiv Gandhi Khel Ratna in 2021",
    ],
  },
  {
    slug: "viren-raquib-athletics-bengaluru",
    name: "Viren Raquib",
    avatar: "/images/coaches/viren-raquib-athletics-bengaluru.svg",
    certifications: [
      { name: "IAAF Level 2 Sprints Coach", issuer: "World Athletics", year: 2017 },
      { name: "NSNIS Diploma in Sports Coaching", issuer: "NSNIS Patiala", year: 2015 },
    ],
    experienceYears: 12,
    sportsCoached: ["athletics"],
    specialization: ["sprints", "relay handoffs", "speed endurance"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 12.9789,
      lng: 77.5996,
    },
    contact: {
      phone: "+91 99 1650 2200",
      email: "viren.athletics@gmail.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 64 },
    status: "published",
    bio: "IAAF-certified sprint coach specializing in developing explosive speed and relay team coordination. Has trained multiple state-level and national-level sprinters.",
    achievements: [
      "Coached athletes to 4 national relay medals in the last 5 years",
      "NSNIS Diploma holder in Athletics Coaching from Patiala",
      "Developed a speed endurance training program adopted by Karnataka Athletics",
      "Mentored over 20 state-level sprint champions",
    ],
  },
  {
    slug: "sushil-kumar-wrestling-delhi",
    name: "Sushil Kumar",
    avatar: "/images/coaches/sushil-kumar-wrestling-delhi.svg",
    certifications: [
      { name: "WFI National Coaching Cert.", issuer: "Wrestling Federation of India", year: 2014 },
    ],
    experienceYears: 16,
    sportsCoached: ["wrestling"],
    specialization: ["freestyle wrestling", "olympic lifting fundamentals", "competition prep"],
    location: {
      city: "Delhi",
      state: "Delhi",
      country: "IN",
      lat: 28.6139,
      lng: 77.209,
    },
    contact: {
      phone: "+91 98 1810 4500",
      email: "coach.sushil@delhiwrestling.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.7, count: 92 },
    status: "published",
    bio: "Two-time Olympic medalist in wrestling who now coaches elite grapplers at the national level. Specializes in freestyle wrestling and Olympic preparation.",
    achievements: [
      "Won Olympic medals in wrestling at 2008 Beijing and 2012 London",
      "Three-time World Wrestling Championship medalist",
      "Recipient of the Rajiv Gandhi Khel Ratna and Padma Shri",
      "Has coached multiple Commonwealth Games medal-winning wrestlers",
    ],
  },
  {
    slug: "mary-kom-boxing-rohtak",
    name: "Mary Kom",
    avatar: "/images/coaches/mary-komar-boxing-rohtak.svg",
    certifications: [
      { name: "AIBA 3-Star Coach", issuer: "International Boxing Association", year: 2016 },
    ],
    experienceYears: 13,
    sportsCoached: ["boxing"],
    specialization: ["flyweight", "footwork", "mental conditioning"],
    location: {
      city: "Rohtak",
      state: "Haryana",
      country: "IN",
      lat: 28.8955,
      lng: 76.6066,
    },
    contact: {
      phone: "+91 98 1801 7890",
      email: "coach.marykom@rohtakboxing.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.8, count: 109 },
    status: "published",
    bio: "Six-time World Amateur Boxing champion and Olympic bronze medalist, now mentoring aspiring boxers across India. Renowned for her relentless fighting spirit and technical skill.",
    achievements: [
      "Won six World Amateur Boxing Championships in the flyweight division",
      "Bronze medalist at the 2012 London Olympics in women's boxing",
      "First Indian woman boxer to qualify for the Olympics",
      "Awarded the Padma Bhushan, Padma Shri, and Rajiv Gandhi Khel Ratna",
    ],
  },
  {
    slug: "arjun-jadhav-table-tennis-pune",
    name: "Arjun Jadhav",
    avatar: "/images/coaches/arjun-jadhav-table-tennis-pune.svg",
    certifications: [
      { name: "ITTF Level 1 Coach", issuer: "International Table Tennis Federation", year: 2019 },
    ],
    experienceYears: 8,
    sportsCoached: ["table-tennis"],
    specialization: ["defensive play", "serve variation", "junior development"],
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "IN",
      lat: 18.5204,
      lng: 73.8567,
    },
    contact: {
      phone: "+91 98 6011 0099",
      email: "arjun.tt@puneacademy.in",
    },
    verificationStatus: "pending",
    rating: { average: 4.4, count: 38 },
    status: "published",
    bio: "ITTF-certified table tennis coach known for developing creative defensive players. Focused on junior development and innovative serve techniques.",
    achievements: [
      "Trained 3 junior national-level table tennis players",
      "ITTF Level 1 certified coach with expertise in defensive tactics",
      "Designed the Pune Junior TT Development curriculum",
      "Won 2 Maharashtra State Senior TT Championships",
    ],
  },
  {
    slug: "ramesh-powar-cricket-bengaluru",
    name: "Ramesh Powar",
    avatar: "/images/coaches/ramesh-powar-cricket-bengaluru.svg",
    certifications: [
      { name: "BCCI Level 2 Coach", issuer: "BCCI", year: 2018 },
    ],
    experienceYears: 12,
    sportsCoached: ["cricket"],
    specialization: ["off-spin bowling", "middle-order batting", "fitness"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 12.9848,
      lng: 77.5850,
    },
    contact: {
      phone: "+91 98 4501 2345",
      email: "ramesh@kioc.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.5, count: 95 },
    status: "published",
    bio: "Former India off-spinner and women's cricket head coach, recognized for building match-winning bowling attacks. Expert in spin bowling variations and match awareness.",
    achievements: [
      "Served as head coach of the Indian women's national cricket team",
      "Took 157 wickets in international cricket across all formats",
      "Guided India Women to the 2020 ICC T20 World Cup final",
      "BCCI Level 2 certified coach with over a decade of coaching experience",
    ],
  },
  {
    slug: "venkatesh-prasad-cricket-bengaluru",
    name: "Venkatesh Prasad",
    avatar: "/images/coaches/venkatesh-prasad-cricket-bengaluru.svg",
    certifications: [
      { name: "BCCI Level 2 Coach", issuer: "BCCI", year: 2016 },
    ],
    experienceYears: 14,
    sportsCoached: ["cricket"],
    specialization: ["fast bowling", "swing bowling", "bowling strategy"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 12.9848,
      lng: 77.5850,
    },
    contact: {
      phone: "+91 98 4501 3456",
      email: "venkatesh@kioc.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 112 },
    status: "published",
    bio: "Former India fast bowler renowned for his mastery of swing and seam bowling. Now coaches fast bowlers and bowling units at the regional and national level.",
    achievements: [
      "Took 96 Test wickets for India, including a famous 6-33 at Chennai",
      "Former bowling coach for the Indian national cricket team",
      "BCCI Level 2 certified fast bowling specialist",
      "Coached the Karnataka state team to multiple Ranji Trophy victories",
    ],
  },
  {
    slug: "jagadeesan-arun-cricket-bengaluru",
    name: "Arun Jagadeesan",
    avatar: "/images/coaches/jagadeesan-arun-cricket-bengaluru.svg",
    certifications: [
      { name: "BCCI Level 1 Coach", issuer: "BCCI", year: 2020 },
    ],
    experienceYears: 8,
    sportsCoached: ["cricket"],
    specialization: ["wicketkeeping", "top-order batting", "fielding"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 13.1077,
      lng: 77.5726,
    },
    contact: {
      phone: "+91 98 4501 4567",
      email: "arun@justcricket.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.3, count: 67 },
    status: "published",
    bio: "BCCI Level 1 certified coach with expertise in wicketkeeping and top-order batting. Dedicated to developing well-rounded cricketers with strong fielding skills.",
    achievements: [
      "Coached Bengaluru Academy wicketkeepers to 2 state-level titles",
      "Developed a specialized wicketkeeping drill program for juniors",
      "Former domestic cricketer with 150+ first-class dismissals",
      "Fielding consultant for Karnataka age-group cricket teams",
    ],
  },
  {
    slug: "sunil-chhetri-football-bengaluru",
    name: "Sunil Chhetri",
    avatar: "/images/coaches/sunil-chhetri-football-bengaluru.svg",
    certifications: [
      { name: "AIFF D License", issuer: "AIFF", year: 2019 },
      { name: "AFC C License", issuer: "AFC", year: 2022 },
    ],
    experienceYears: 10,
    sportsCoached: ["football"],
    specialization: ["striker development", "goal scoring", "leadership"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 13.0720,
      lng: 77.5930,
    },
    contact: {
      phone: "+91 98 4501 5678",
      email: "sunil@bfa.ac.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.8, count: 189 },
    status: "published",
    bio: "India's all-time leading goalscorer and one of the most celebrated footballers in South Asian history. Now mentors young strikers and develops attacking talent.",
    achievements: [
      "Holds the record for most international goals by an Asian male player (94)",
      "Led India to multiple SAFF Championship titles as captain",
      "Awarded the Padma Shri and Arjuna Award for football",
      "Scored in four consecutive AFC Asian Cup campaigns",
    ],
  },
  {
    slug: "gurpreet-singh-sandhu-football-bengaluru",
    name: "Gurpreet Singh Sandhu",
    avatar: "/images/coaches/gurpreet-singh-sandhu-football-bengaluru.svg",
    certifications: [
      { name: "AIFF D License", issuer: "AIFF", year: 2020 },
    ],
    experienceYears: 8,
    sportsCoached: ["football"],
    specialization: ["goalkeeping", "shot-stopping", "distribution"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 12.9615,
      lng: 77.5946,
    },
    contact: {
      phone: "+91 98 4501 6789",
      email: "gurpreet@bfc.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 134 },
    status: "published",
    bio: "First Indian footballer to play in the UEFA Europa League, now developing the next generation of goalkeepers. Known for his shot-stopping ability and commanding presence.",
    achievements: [
      "First Indian to play in a UEFA Europa League group stage match",
      "Won multiple I-League and ISL titles as a goalkeeper",
      "Over 50 international caps for India",
      "AIFF D License holder and goalkeeping development specialist",
    ],
  },
  {
    slug: "prakash-padukone-badminton-bengaluru",
    name: "Prakash Padukone",
    avatar: "/images/coaches/prakash-padukone-badminton-bengaluru.svg",
    certifications: [
      { name: "BWF Coach Education", issuer: "BWF", year: 2015 },
    ],
    experienceYears: 20,
    sportsCoached: ["badminton"],
    specialization: ["all-round development", "mental toughness", "international competition"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 13.1050,
      lng: 77.5700,
    },
    contact: {
      phone: "+91 98 4501 7890",
      email: "prakash@padukonedravid.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.9, count: 256 },
    status: "published",
    bio: "India's first badminton world champion who built the Padukone-Dravid Academy into a premier training center. Renowned for instilling mental toughness and international standards.",
    achievements: [
      "First Indian to win the All England Open Badminton Championships",
      "Won the World Badminton Championships bronze medal in 1983",
      "Founded the Prakash Padukone Badminton Academy in Bengaluru",
      "Received the Padma Shri, Padma Bhushan, and Arjuna Award",
    ],
  },
  {
    slug: "mahesh-bhupathi-tennis-bengaluru",
    name: "Mahesh Bhupathi",
    avatar: "/images/coaches/mahesh-bhupathi-tennis-bengaluru.svg",
    certifications: [
      { name: "ITF Level 2 Coach", issuer: "ITF", year: 2017 },
    ],
    experienceYears: 12,
    sportsCoached: ["tennis"],
    specialization: ["doubles", "serve-and-volley", "net play"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 12.9776,
      lng: 77.5878,
    },
    contact: {
      phone: "+91 98 4501 8901",
      email: "mahesh@kslta.org",
    },
    verificationStatus: "verified",
    rating: { average: 4.7, count: 145 },
    status: "published",
    bio: "One of India's most successful doubles tennis players with 12 Grand Slam titles. Now developing doubles specialists and mentoring young tennis talent through his academy.",
    achievements: [
      "Won 12 Grand Slam doubles titles in men's and mixed doubles",
      "Former world No. 1 doubles player on the ATP Tour",
      "Founded the Mahesh Bhupathi Tennis Academies across India",
      "Awarded the Padma Shri for contributions to Indian tennis",
    ],
  },
  {
    slug: "akanksha-singh-basketball-bengaluru",
    name: "Akanksha Singh",
    avatar: "/images/coaches/akanksha-singh-basketball-bengaluru.svg",
    certifications: [
      { name: "BAI Level 2 Coach", issuer: "BAI", year: 2018 },
    ],
    experienceYears: 12,
    sportsCoached: ["basketball"],
    specialization: ["guard play", "ball handling", "youth development"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 13.0950,
      lng: 77.5650,
    },
    contact: {
      phone: "+91 98 4501 9012",
      email: "akanksha@akankshabasketball.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 123 },
    status: "published",
    bio: "Former India women's basketball team captain turned coach, passionate about developing guard skills and youth basketball programs. Known for her high-energy training sessions.",
    achievements: [
      "Former captain of the Indian women's national basketball team",
      "Won 5 consecutive WNBL titles as a player",
      "BAI Level 2 certified basketball coach",
      "Developed a guard development program used by 12 academies",
    ],
  },
  {
    slug: "nisha-millet-swimming-bengaluru",
    name: "Nisha Millet",
    avatar: "/images/coaches/nisha-millet-swimming-bengaluru.svg",
    certifications: [
      { name: "ASCA Level 3 Coach", issuer: "ASCA", year: 2016 },
    ],
    experienceYears: 15,
    sportsCoached: ["swimming"],
    specialization: ["freestyle", "butterfly", "sprint events"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 12.9784,
      lng: 77.6408,
    },
    contact: {
      phone: "+91 98 4502 0123",
      email: "nisha@nishamilletswimming.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.8, count: 178 },
    status: "published",
    bio: "Four-time Asian Games medalist in swimming, now one of India's leading swim coaches. Specializes in freestyle and butterfly sprint events with a focus on technique refinement.",
    achievements: [
      "Won 4 medals at the Asian Games in swimming",
      "Set 2 national records in freestyle and butterfly events",
      "ASCA Level 3 certified coach with 15 years of experience",
      "Trained over 30 state-level and national-level swimmers",
    ],
  },
  {
    slug: "pullela-gopichand-badminton-hyderabad",
    name: "Pullela Gopichand",
    avatar: "/images/coaches/pullela-gopichand-badminton-hyderabad.svg",
    certifications: [
      { name: "BWF Coach Education Level 2", issuer: "BWF", year: 2014 },
    ],
    experienceYears: 18,
    sportsCoached: ["badminton"],
    specialization: ["all-round development", "Olympic preparation", "mental conditioning"],
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "IN",
      lat: 17.4399,
      lng: 78.3569,
    },
    contact: {
      phone: "+91 98 4801 2345",
      email: "gopi@pgbadminton.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.9, count: 312 },
    status: "published",
    bio: "One of India's greatest badminton coaches, credited with producing multiple Olympic and world-class players from his academy. Known for his rigorous training methods and mental conditioning.",
    achievements: [
      "Coached Saina Nehwal and PV Sindhu to Olympic medals",
      "Founded the Pullela Gopichand Badminton Academy in Hyderabad",
      "Won the All England Open Badminton Championships as a player",
      "Received the Padma Bhushan, Dronacharya Award, and Khel Ratna",
    ],
  },
  {
    slug: "msk-prasad-cricket-hyderabad",
    name: "MSK Prasad",
    avatar: "/images/coaches/msk-prasad-cricket-hyderabad.svg",
    certifications: [
      { name: "BCCI Level 2 Coach", issuer: "BCCI", year: 2015 },
    ],
    experienceYears: 14,
    sportsCoached: ["cricket"],
    specialization: ["wicketkeeping", "team management", "selection strategy"],
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "IN",
      lat: 17.4400,
      lng: 78.3489,
    },
    contact: {
      phone: "+91 98 4801 3456",
      email: "msk@mskprasadacademy.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.5, count: 98 },
    status: "published",
    bio: "Former India wicketkeeper-batsman and chief selector, now running one of Hyderabad's premier cricket academies. Expert in wicketkeeping technique and talent identification.",
    achievements: [
      "Played 17 international matches for India as wicketkeeper-batsman",
      "Served as BCCI chief selector from 2016 to 2020",
      "Founded the MSK Prasad Cricket Academy in Hyderabad",
      "BCCI Level 2 certified coach with 14 years of coaching experience",
    ],
  },
  {
    slug: "sania-mirza-tennis-hyderabad",
    name: "Sania Mirza",
    avatar: "/images/coaches/sania-mirza-tennis-hyderabad.svg",
    certifications: [
      { name: "ITF Level 1 Coach", issuer: "ITF", year: 2020 },
    ],
    experienceYears: 10,
    sportsCoached: ["tennis"],
    specialization: ["doubles", "baseline game", "mental resilience"],
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "IN",
      lat: 17.4156,
      lng: 78.4347,
    },
    contact: {
      phone: "+91 98 4801 4567",
      email: "sania@leelagetennis.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.7, count: 167 },
    status: "published",
    bio: "India's most successful female tennis player and former world No. 1 in doubles. Now mentoring young tennis players and promoting the sport across the country.",
    achievements: [
      "Former world No. 1 in women's doubles tennis",
      "Won 6 Grand Slam doubles titles",
      "First Indian woman to reach the WTA Tour finals in singles",
      "Awarded the Padma Shri, Padma Bhushan, and Rajiv Gandhi Khel Ratna",
    ],
  },
  {
    slug: "vvs-laxman-cricket-hyderabad",
    name: "VVS Laxman",
    avatar: "/images/coaches/vvs-laxman-cricket-hyderabad.svg",
    certifications: [
      { name: "BCCI Level 3 Coach", issuer: "BCCI", year: 2019 },
    ],
    experienceYears: 16,
    sportsCoached: ["cricket"],
    specialization: ["batting technique", "middle-order play", "cricket aesthetics"],
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "IN",
      lat: 17.4400,
      lng: 78.5000,
    },
    contact: {
      phone: "+91 98 4801 5678",
      email: "laxman@hca-cricket.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.8, count: 198 },
    status: "published",
    bio: "India's batting maestro known for his elegant stroke play and match-saving innings. Now mentors young batsmen at his cricket academy in Hyderabad and heads the NCA.",
    achievements: [
      "Scored 8,781 runs in Test cricket with 17 centuries",
      "Hit the famous 281 not out at Eden Gardens, widely regarded as India's greatest Test innings",
      "Serves as head of the National Cricket Academy in Bengaluru",
      "Recipient of the Padma Shri and Arjuna Award",
    ],
  },
  {
    slug: "saina-nehwal-badminton-hyderabad-2",
    name: "Saina Nehwal",
    avatar: "/images/coaches/saina-nehwal-badminton-hyderabad-2.svg",
    certifications: [
      { name: "BWF Coach Education Level 2", issuer: "BWF", year: 2019 },
    ],
    experienceYears: 8,
    sportsCoached: ["badminton"],
    specialization: ["singles", "aggressive play", "fitness"],
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "IN",
      lat: 17.4399,
      lng: 78.3569,
    },
    contact: {
      phone: "+91 98 4801 6789",
      email: "saina@pgbadminton.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.7, count: 156 },
    status: "published",
    bio: "Olympic medalist badminton player turned coach, specializing in aggressive singles play and peak physical fitness. Continues to develop top talent from the Gopichand Academy.",
    achievements: [
      "Won the 2015 All England Open Badminton Championships",
      "Bronze medalist at the 2012 London Olympics",
      "Multiple-time national champion in women's singles",
      "BWF Coach Education Level 2 certified professional",
    ],
  },
  {
    slug: "ravi-shastri-cricket-chennai",
    name: "Ravi Shastri",
    avatar: "/images/coaches/ravi-shastri-cricket-chennai.svg",
    certifications: [
      { name: "BCCI Level 3 Coach", issuer: "BCCI", year: 2017 },
    ],
    experienceYears: 20,
    sportsCoached: ["cricket"],
    specialization: ["team management", "fast bowling", "leadership"],
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "IN",
      lat: 13.0628,
      lng: 80.2790,
    },
    contact: {
      phone: "+91 98 4301 2345",
      email: "ravi@tnca.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.8, count: 234 },
    status: "published",
    bio: "Former India all-rounder and successful head coach who led the team to numerous overseas victories. Known for his bold team management approach and motivational skills.",
    achievements: [
      "Head coach of India during the historic 2018-19 Test series win in Australia",
      "Coached India to the 2019 ICC Cricket World Cup semi-finals",
      "Scored 11 Test centuries and took 48 wickets as a player",
      "Former team director and mentor of the Indian cricket team",
    ],
  },
  {
    slug: "sachin-tendulkar-cricket-mumbai",
    name: "Sachin Tendulkar",
    avatar: "/images/coaches/sachin-tendulkar-cricket-mumbai.svg",
    certifications: [
      { name: "BCCI Level 3 Coach", issuer: "BCCI", year: 2018 },
    ],
    experienceYears: 15,
    sportsCoached: ["cricket"],
    specialization: ["batting masterclass", "technique", "mental game"],
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "IN",
      lat: 18.9388,
      lng: 72.8258,
    },
    contact: {
      phone: "+91 98 2101 2345",
      email: "sachin@mca-cricket.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.9, count: 345 },
    status: "published",
    bio: "The \"God of Cricket\" and highest run-scorer in international cricket history. Now coaching batting masterclasses and mentoring young cricketers through his academy.",
    achievements: [
      "Scored 15,921 Test runs and 18,426 ODI runs, the most in cricket history",
      "First player to score 100 international centuries",
      "Awarded the Bharat Ratna, India's highest civilian honor",
      "Won the 2011 ICC Cricket World Cup with India",
    ],
  },
  {
    slug: "sunil-gavaskar-cricket-mumbai",
    name: "Sunil Gavaskar",
    avatar: "/images/coaches/sunil-gavaskar-cricket-mumbai.svg",
    certifications: [
      { name: "BCCI Level 2 Coach", issuer: "BCCI", year: 2016 },
    ],
    experienceYears: 18,
    sportsCoached: ["cricket"],
    specialization: ["opening batting", "technique", "match awareness"],
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "IN",
      lat: 18.9388,
      lng: 72.8258,
    },
    contact: {
      phone: "+91 98 2101 3456",
      email: "sunil@mca-cricket.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.8, count: 267 },
    status: "published",
    bio: "One of cricket's greatest opening batsmen who revolutionized Test batting in the 1970s and 80s. Now shares his technical expertise and match awareness as a senior coach.",
    achievements: [
      "First batsman to score 10,000 Test runs",
      "Held the record for most Test runs (10,122) for over two decades",
      "Won the Wisden Cricketer of the Year award twice",
      "Awarded the Padma Shri and BCCI Lifetime Achievement Award",
    ],
  },
  {
    slug: "baichung-bhutia-football-mumbai",
    name: "Baichung Bhutia",
    avatar: "/images/coaches/baichung-bhutia-football-mumbai.svg",
    certifications: [
      { name: "AIFF D License", issuer: "AIFF", year: 2018 },
      { name: "AFC C License", issuer: "AFC", year: 2021 },
    ],
    experienceYears: 12,
    sportsCoached: ["football"],
    specialization: ["striker development", "hold-up play", "movement off the ball"],
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "IN",
      lat: 19.1364,
      lng: 72.8296,
    },
    contact: {
      phone: "+91 98 2101 4567",
      email: "baichung@footballschoolofindia.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 143 },
    status: "published",
    bio: "The \"Sikkimese Sniper\" and India's former talisman striker, now developing young football talent through his Football School of India. Known for his clinical finishing.",
    achievements: [
      "Scored 42 goals for the Indian national football team",
      "Led India to victory in the 2008 AFC Challenge Cup",
      "First Asian footballer to play in England's Premier League",
      "Awarded the Padma Shri and AIFF Player of the Year multiple times",
    ],
  },
  {
    slug: "michael-phelps-swimming-mumbai",
    name: "Michael Phelps",
    avatar: "/images/coaches/michael-phelps-swimming-mumbai.svg",
    certifications: [
      { name: "ASCA Level 5 Coach", issuer: "ASCA", year: 2015 },
    ],
    experienceYears: 10,
    sportsCoached: ["swimming"],
    specialization: ["butterfly", "individual medley", "race strategy"],
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "IN",
      lat: 19.1360,
      lng: 72.8420,
    },
    contact: {
      phone: "+91 98 2101 5678",
      email: "michael@michaelphelesswimming.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.9, count: 289 },
    status: "published",
    bio: "The most decorated Olympian of all time with 28 Olympic medals, now coaching elite swimmers. Brings unmatched expertise in butterfly and individual medley events.",
    achievements: [
      "Won 28 Olympic medals, including 23 gold medals",
      "Holds the world record in 5 individual swimming events",
      "ASCA Level 5 certified, the highest coaching level",
      "Named World Swimmer of the Year 8 times",
    ],
  },
  {
    slug: "kapil-dev-cricket-delhi",
    name: "Kapil Dev",
    avatar: "/images/coaches/kapil-dev-cricket-delhi.svg",
    certifications: [
      { name: "BCCI Level 3 Coach", issuer: "BCCI", year: 2015 },
    ],
    experienceYears: 22,
    sportsCoached: ["cricket"],
    specialization: ["fast bowling", "all-round development", "leadership"],
    location: {
      city: "Delhi",
      state: "Delhi",
      country: "IN",
      lat: 28.6376,
      lng: 77.2430,
    },
    contact: {
      phone: "+91 98 1101 2345",
      email: "kapil@ddca.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.9, count: 312 },
    status: "published",
    bio: "India's 1983 World Cup-winning captain and one of cricket's greatest all-rounders. Now coaching fast bowlers and developing all-round cricketers at his academy.",
    achievements: [
      "Led India to their first Cricket World Cup victory in 1983",
      "First player to take 400 wickets and score 5,000 runs in Tests",
      "Held the record for most Test wickets (434) at the time of retirement",
      "Awarded the Padma Shri, Padma Bhushan, and Wisden Cricketer of the Year",
    ],
  },
  {
    slug: "sourav-ganguly-cricket-delhi",
    name: "Sourav Ganguly",
    avatar: "/images/coaches/sourav-ganguly-cricket-delhi.svg",
    certifications: [
      { name: "BCCI Level 2 Coach", issuer: "BCCI", year: 2017 },
    ],
    experienceYears: 16,
    sportsCoached: ["cricket"],
    specialization: ["left-hand batting", "aggressive captaincy", "team building"],
    location: {
      city: "Delhi",
      state: "Delhi",
      country: "IN",
      lat: 28.6376,
      lng: 77.2430,
    },
    contact: {
      phone: "+91 98 1101 3456",
      email: "sourav@ddca.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.7, count: 198 },
    status: "published",
    bio: "The \"Prince of Kolkata\" who transformed Indian cricket with his aggressive captaincy. Now mentoring young cricketers and leading cricket administration as BCCI president.",
    achievements: [
      "Led India to the 2003 ICC Cricket World Cup final",
      "Transformed India into a formidable overseas Test team",
      "Scored 7,212 runs in Test cricket with 16 centuries",
      "Currently serves as president of the Board of Control for Cricket in India",
    ],
  },
  {
    slug: "gagan-narang-shooting-delhi",
    name: "Gagan Narang",
    avatar: "/images/coaches/gagan-narang-shooting-delhi.svg",
    certifications: [
      { name: "NRAI Certified Coach", issuer: "NRAI", year: 2018 },
    ],
    experienceYears: 12,
    sportsCoached: ["shooting"],
    specialization: ["air rifle", "precision shooting", "mental focus"],
    location: {
      city: "Delhi",
      state: "Delhi",
      country: "IN",
      lat: 28.5800,
      lng: 77.0450,
    },
    contact: {
      phone: "+91 98 1101 4567",
      email: "gagan@pushsports.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 87 },
    status: "published",
    bio: "Olympic bronze medalist in shooting who now coaches precision shooters at the elite level. Expert in air rifle technique and the mental aspects of competitive shooting.",
    achievements: [
      "Won a bronze medal in the 10m air rifle event at the 2012 London Olympics",
      "Holds the world record in 10m air rifle with a perfect 600 qualification score",
      "Won 5 gold medals at the Commonwealth Games",
      "Awarded the Padma Shri and Arjuna Award for shooting",
    ],
  },
  {
    slug: "dilip-vengsarkar-cricket-pune",
    name: "Dilip Vengsarkar",
    avatar: "/images/coaches/dilip-vengsarkar-cricket-pune.svg",
    certifications: [
      { name: "BCCI Level 3 Coach", issuer: "BCCI", year: 2016 },
    ],
    experienceYears: 18,
    sportsCoached: ["cricket"],
    specialization: ["middle-order batting", "technique", "youth mentorship"],
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "IN",
      lat: 18.5074,
      lng: 73.8077,
    },
    contact: {
      phone: "+91 98 2301 2345",
      email: "dilip@vengsarkaracademy.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.7, count: 156 },
    status: "published",
    bio: "Former India middle-order batsman and chief selector known for his elegant technique. Now mentoring young cricketers through his academy in Pune.",
    achievements: [
      "Scored 6,868 runs in Test cricket with 17 centuries",
      "Served as BCCI chief selector for two terms",
      "Won the 1983 Cricket World Cup as a key member of the squad",
      "Established the Dilip Vengsarkar Cricket Academy in Pune",
    ],
  },
  {
    slug: "rahul-dravid-cricket-pune",
    name: "Rahul Dravid",
    avatar: "/images/coaches/rahul-dravid-cricket-pune.svg",
    certifications: [
      { name: "BCCI Level 3 Coach", issuer: "BCCI", year: 2019 },
    ],
    experienceYears: 14,
    sportsCoached: ["cricket"],
    specialization: ["batting technique", "youth development", "mental preparation"],
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "IN",
      lat: 18.4700,
      lng: 73.8300,
    },
    contact: {
      phone: "+91 98 2301 3456",
      email: "rahul@kshetram.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.8, count: 189 },
    status: "published",
    bio: "One of cricket's most respected coaches and former India captain, known as \"The Wall.\" Specializes in batting technique and building mentally resilient cricketers.",
    achievements: [
      "Coached India U-19 to the 2016 ICC U-19 World Cup runners-up finish",
      "Served as head coach of the Indian senior team",
      "Scored 13,288 Test runs with 36 centuries",
      "Received the Padma Shri and ICC Cricketer of the Year award",
    ],
  },
  {
    slug: "bhaichung-bhutia-football-pune",
    name: "Bhaichung Bhutia",
    avatar: "/images/coaches/bhaichung-bhutia-football-pune.svg",
    certifications: [
      { name: "AIFF D License", issuer: "AIFF", year: 2019 },
      { name: "AFC C License", issuer: "AFC", year: 2022 },
    ],
    experienceYears: 10,
    sportsCoached: ["football"],
    specialization: ["striker development", "hold-up play", "movement off the ball"],
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "IN",
      lat: 18.5530,
      lng: 73.9400,
    },
    contact: {
      phone: "+91 98 2301 4567",
      email: "bhaichung@asgfootball.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.5, count: 112 },
    status: "published",
    bio: "India's legendary striker known as the \"Sikkimese Sniper,\" now developing young football talent in Pune. Focused on striker movement and clinical finishing.",
    achievements: [
      "Scored 42 goals for the Indian national football team",
      "Won the AFC Challenge Cup with India in 2008",
      "First Asian to play in the English Premier League",
      "Multiple-time AIFF Player of the Year",
    ],
  },
  {
    slug: "saina-nehwal-badminton-pune",
    name: "Saina Nehwal",
    avatar: "/images/coaches/saina-nehwal-badminton-pune.svg",
    certifications: [
      { name: "BWF Coach Education Level 2", issuer: "BWF", year: 2020 },
    ],
    experienceYears: 7,
    sportsCoached: ["badminton"],
    specialization: ["singles", "aggressive play", "fitness"],
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "IN",
      lat: 18.5080,
      lng: 73.8085,
    },
    contact: {
      phone: "+91 98 2301 5678",
      email: "saina@badmintonpune.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 134 },
    status: "published",
    bio: "Olympic medalist and former world No. 1 in badminton singles, coaching aggressive play style in Pune. Brings international-level training to the local badminton scene.",
    achievements: [
      "Bronze medalist at the 2012 London Olympics",
      "Won the 2015 All England Open Badminton Championships",
      "First Indian to win the World Junior Badminton Championships",
      "Awarded the Padma Shri and Rajiv Gandhi Khel Ratna",
    ],
  },
  {
    slug: "virender-sehwag-cricket-vijayawada",
    name: "Virender Sehwag",
    avatar: "/images/coaches/virender-sehwag-cricket-vijayawada.svg",
    certifications: [
      { name: "BCCI Level 2 Coach", issuer: "BCCI", year: 2018 },
    ],
    experienceYears: 12,
    sportsCoached: ["cricket"],
    specialization: ["aggressive batting", "opening partnerships", "match awareness"],
    location: {
      city: "Vijayawada",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 16.5062,
      lng: 80.6480,
    },
    contact: {
      phone: "+91 98 4801 2345",
      email: "viru@vijayawadacricket.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.7, count: 145 },
    status: "published",
    bio: "India's most destructive opening batsman who redefined attacking cricket. Now coaching explosive batting and aggressive opening partnerships at his academy.",
    achievements: [
      "Scored 8,586 Test runs with 23 centuries at a strike rate of 82.23",
      "One of only 4 batsmen to score 100 runs on ODI debut",
      "Held the record for the fastest Test triple century (281 balls)",
      "Awarded the Arjuna Award and Wisden Cricketer of the Year",
    ],
  },
  {
    slug: "sourav-ganguly-cricket-vijayawada",
    name: "Sourav Ganguly",
    avatar: "/images/coaches/sourav-ganguly-cricket-vijayawada.svg",
    certifications: [
      { name: "BCCI Level 2 Coach", issuer: "BCCI", year: 2019 },
    ],
    experienceYears: 14,
    sportsCoached: ["cricket"],
    specialization: ["left-hand batting", "aggressive captaincy", "team building"],
    location: {
      city: "Vijayawada",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 16.5040,
      lng: 80.6350,
    },
    contact: {
      phone: "+91 98 4801 3456",
      email: "saurav@andhracricketacademy.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 123 },
    status: "published",
    bio: "The aggressive former India captain who instilled a winning mentality in Indian cricket. Coaching captaincy skills and team building at the Andhra Cricket Academy.",
    achievements: [
      "Led India to the 2003 ICC Cricket World Cup final",
      "Transformed India into a competitive overseas Test team",
      "Scored 7,212 Test runs and 11,363 ODI runs",
      "Currently serves as BCCI president",
    ],
  },
  {
    slug: "baichung-bhutia-football-vijayawada",
    name: "Bhaichung Bhutia",
    avatar: "/images/coaches/baichung-bhutia-football-vijayawada.svg",
    certifications: [
      { name: "AIFF D License", issuer: "AIFF", year: 2020 },
    ],
    experienceYears: 8,
    sportsCoached: ["football"],
    specialization: ["striker development", "hold-up play", "youth training"],
    location: {
      city: "Vijayawada",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 16.5100,
      lng: 80.6200,
    },
    contact: {
      phone: "+91 98 4801 4567",
      email: "bhaichung@vijayawadafootball.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.4, count: 87 },
    status: "published",
    bio: "India's former talisman striker bringing youth football development to Vijayawada. Specializes in developing young forwards with strong hold-up play skills.",
    achievements: [
      "Scored 42 goals for the Indian national football team",
      "Won the AFC Challenge Cup with India in 2008",
      "Multiple-time I-League champion as a player",
      "AIFF D License certified youth football developer",
    ],
  },
  {
    slug: "saina-nehwal-badminton-vijayawada",
    name: "Saina Nehwal",
    avatar: "/images/coaches/saina-nehwal-badminton-vijayawada.svg",
    certifications: [
      { name: "BWF Coach Education Level 1", issuer: "BWF", year: 2021 },
    ],
    experienceYears: 6,
    sportsCoached: ["badminton"],
    specialization: ["singles", "footwork", "rally endurance"],
    location: {
      city: "Vijayawada",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 16.4900,
      lng: 80.6700,
    },
    contact: {
      phone: "+91 98 4801 5678",
      email: "saina@vbadminton.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.5, count: 98 },
    status: "published",
    bio: "Olympic medalist and former world No. 1 in badminton singles, coaching footwork and endurance in Vijayawada. BWF Level 1 certified professional.",
    achievements: [
      "Bronze medalist at the 2012 London Olympics",
      "First Indian to win the World Junior Badminton Championships",
      "Won the 2015 All England Open",
      "BWF Coach Education Level 1 certified",
    ],
  },
  {
    slug: "mahesh-bhupathi-tennis-vijayawada",
    name: "Mahesh Bhupathi",
    avatar: "/images/coaches/mahesh-bhupathi-tennis-vijayawada.svg",
    certifications: [
      { name: "ITF Level 1 Coach", issuer: "ITF", year: 2020 },
    ],
    experienceYears: 10,
    sportsCoached: ["tennis"],
    specialization: ["doubles", "serve-and-volley", "net play"],
    location: {
      city: "Vijayawada",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 16.5030,
      lng: 80.6400,
    },
    contact: {
      phone: "+91 98 4801 6789",
      email: "mahesh@vijayawadatennis.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.5, count: 87 },
    status: "published",
    bio: "Grand Slam-winning doubles specialist now coaching serve-and-volley tennis in Vijayawada. ITF Level 1 certified with extensive doubles expertise.",
    achievements: [
      "Won 12 Grand Slam doubles titles across men's and mixed doubles",
      "Former world No. 1 in doubles",
      "First Indian to reach a Grand Slam singles final",
      "ITF Level 1 certified tennis professional",
    ],
  },
  {
    slug: "kapil-dev-cricket-visakhapatnam",
    name: "Kapil Dev",
    avatar: "/images/coaches/kapil-dev-cricket-visakhapatnam.svg",
    certifications: [
      { name: "BCCI Level 2 Coach", issuer: "BCCI", year: 2017 },
    ],
    experienceYears: 18,
    sportsCoached: ["cricket"],
    specialization: ["fast bowling", "all-round development", "leadership"],
    location: {
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 17.7215,
      lng: 83.3014,
    },
    contact: {
      phone: "+91 98 4801 7890",
      email: "kapil@vizagcricket.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.7, count: 156 },
    status: "published",
    bio: "India's 1983 World Cup-winning captain coaching fast bowlers and all-rounders in Visakhapatnam. Brings legendary all-round expertise to the next generation.",
    achievements: [
      "Led India to the 1983 Cricket World Cup victory",
      "First player to achieve 400 Test wickets and 5,000 Test runs",
      "Held the record for most Test wickets at retirement",
      "Awarded the Padma Shri and Padma Bhushan",
    ],
  },
  {
    slug: "mahesh-bhupathi-tennis-visakhapatnam",
    name: "Mahesh Bhupathi",
    avatar: "/images/coaches/mahesh-bhupathi-tennis-visakhapatnam.svg",
    certifications: [
      { name: "ITF Level 2 Coach", issuer: "ITF", year: 2018 },
    ],
    experienceYears: 12,
    sportsCoached: ["tennis"],
    specialization: ["doubles", "serve-and-volley", "net play"],
    location: {
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 17.7100,
      lng: 83.3050,
    },
    contact: {
      phone: "+91 98 4801 8901",
      email: "mahesh@advancetennis.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 112 },
    status: "published",
    bio: "Grand Slam-winning doubles specialist with ITF Level 2 certification, developing tennis talent in Visakhapatnam. Expert in doubles strategy and net play.",
    achievements: [
      "Won 12 Grand Slam doubles titles",
      "Former world No. 1 in men's doubles",
      "Padma Shri recipient for contributions to tennis",
      "ITF Level 2 certified with over a decade of coaching",
    ],
  },
  {
    slug: "saina-nehwal-badminton-visakhapatnam",
    name: "Saina Nehwal",
    avatar: "/images/coaches/saina-nehwal-badminton-visakhapatnam.svg",
    certifications: [
      { name: "BWF Coach Education Level 1", issuer: "BWF", year: 2020 },
    ],
    experienceYears: 7,
    sportsCoached: ["badminton"],
    specialization: ["singles", "footwork", "rally endurance"],
    location: {
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 17.7250,
      lng: 83.2900,
    },
    contact: {
      phone: "+91 98 4801 9012",
      email: "saina@vizagbadminton.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.5, count: 98 },
    status: "published",
    bio: "Olympic medalist badminton player coaching singles specialists in Visakhapatnam. BWF Level 1 certified with focus on footwork and endurance training.",
    achievements: [
      "Bronze medalist at the 2012 London Olympics",
      "First Indian to win the World Junior Badminton Championships",
      "Multiple-time national champion",
      "BWF Coach Education Level 1 certified",
    ],
  },
  {
    slug: "baichung-bhutia-football-visakhapatnam",
    name: "Bhaichung Bhutia",
    avatar: "/images/coaches/baichung-bhutia-football-visakhapatnam.svg",
    certifications: [
      { name: "AIFF D License", issuer: "AIFF", year: 2019 },
    ],
    experienceYears: 9,
    sportsCoached: ["football"],
    specialization: ["striker development", "hold-up play", "youth training"],
    location: {
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 17.7160,
      lng: 83.3200,
    },
    contact: {
      phone: "+91 98 4802 0123",
      email: "bhaichung@vizagfootball.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.4, count: 87 },
    status: "published",
    bio: "India's legendary striker developing youth football talent in Visakhapatnam. AIFF D License certified with a focus on striker development.",
    achievements: [
      "Scored 42 goals for the Indian national football team",
      "Led India to the 2008 AFC Challenge Cup victory",
      "Multiple-time I-League champion as a player",
      "AIFF D License certified youth football coach",
    ],
  },
  {
    slug: "nisha-millet-swimming-visakhapatnam",
    name: "Nisha Millet",
    avatar: "/images/coaches/nisha-millet-swimming-visakhapatnam.svg",
    certifications: [
      { name: "ASCA Level 2 Coach", issuer: "ASCA", year: 2019 },
    ],
    experienceYears: 10,
    sportsCoached: ["swimming"],
    specialization: ["freestyle", "butterfly", "sprint events"],
    location: {
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 17.7830,
      lng: 83.3780,
    },
    contact: {
      phone: "+91 98 4802 1234",
      email: "nisha@vizagswimming.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.5, count: 98 },
    status: "published",
    bio: "Asian Games medalist swimmer coaching freestyle and butterfly sprinters in Visakhapatnam. ASCA Level 2 certified with a focus on sprint technique.",
    achievements: [
      "Won 4 medals at the Asian Games in swimming",
      "Set 2 national records in freestyle and butterfly",
      "ASCA Level 2 certified swimming coach",
      "Trained over 30 state and national level swimmers",
    ],
  },
  {
    slug: "virdhawal-khade-swimming-bengaluru",
    name: "Virdhawal Khade",
    avatar: "/images/coaches/virdhawal-khade-swimming-bengaluru.svg",
    certifications: [
      { name: "ASCA Level 3 Coach", issuer: "ASCA", year: 2017 },
    ],
    experienceYears: 14,
    sportsCoached: ["swimming"],
    specialization: ["freestyle", "backstroke", "sprint events"],
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "IN",
      lat: 12.9416,
      lng: 77.5790,
    },
    contact: {
      phone: "+91 98 4502 2345",
      email: "virdhawal@bengaluswimming.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 134 },
    status: "published",
    bio: "Asian Games medalist in swimming and one of India's fastest sprinters in the pool. Now coaching freestyle and backstroke specialists with ASCA Level 3 expertise.",
    achievements: [
      "Won a bronze medal at the 2010 Asian Games in the 50m backstroke",
      "Set multiple national records in freestyle and backstroke events",
      "ASCA Level 3 certified swimming coach",
      "Trained swimmers who competed at the 2020 Olympics",
    ],
  },
  {
    slug: "amritpal-singh-basketball-hyderabad",
    name: "Amritpal Singh",
    avatar: "/images/coaches/amritpal-singh-basketball-hyderabad.svg",
    certifications: [
      { name: "FIBA Asia Coaching Cert.", issuer: "FIBA Asia", year: 2018 },
    ],
    experienceYears: 11,
    sportsCoached: ["basketball"],
    specialization: ["center play", "rebounding", "post moves"],
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "IN",
      lat: 17.4350,
      lng: 78.3520,
    },
    contact: {
      phone: "+91 98 4801 7890",
      email: "amritpal@dunkit.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.5, count: 112 },
    status: "published",
    bio: "One of India's tallest basketball players turned coach, specializing in center play and post moves. FIBA Asia certified with over a decade of coaching experience.",
    achievements: [
      "FIBA Asia Coaching Certificate holder",
      "Former India national basketball team player at 7'1\"",
      "Coached Hyderabad basketball to 3 state championships",
      "Developed a post-play curriculum used by 8 Indian basketball academies",
    ],
  },
  {
    slug: "leander-paes-tennis-chennai",
    name: "Leander Paes",
    avatar: "/images/coaches/leander-paes-tennis-chennai.svg",
    certifications: [
      { name: "ITF Level 2 Coach", issuer: "ITF", year: 2016 },
    ],
    experienceYears: 16,
    sportsCoached: ["tennis"],
    specialization: ["doubles", "net play", "mental toughness"],
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "IN",
      lat: 13.0604,
      lng: 80.2490,
    },
    contact: {
      phone: "+91 98 4301 3456",
      email: "leander@sdattennis.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.8, count: 198 },
    status: "published",
    bio: "India's most decorated doubles tennis player with 18 Grand Slam titles. Known for his incredible net play and mental toughness, now coaching the next generation.",
    achievements: [
      "Won 18 Grand Slam titles across doubles and mixed doubles",
      "Held the world No. 1 ranking in doubles",
      "Won 8 Davis Cup doubles rubbers for India",
      "Awarded the Padma Shri, Padma Bhushan, and Rajiv Gandhi Khel Ratna",
    ],
  },
  {
    slug: "rehan-poncha-swimming-mumbai",
    name: "Rehan Poncha",
    avatar: "/images/coaches/rehan-poncha-swimming-mumbai.svg",
    certifications: [
      { name: "ASCA Level 3 Coach", issuer: "ASCA", year: 2016 },
    ],
    experienceYears: 12,
    sportsCoached: ["swimming"],
    specialization: ["butterfly", "individual medley", "distance events"],
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "IN",
      lat: 19.1136,
      lng: 72.8656,
    },
    contact: {
      phone: "+91 98 2101 6789",
      email: "rehan@sportiqo.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.5, count: 109 },
    status: "published",
    bio: "Former national champion swimmer and ASCA Level 3 certified coach specializing in butterfly and individual medley. Develops well-rounded swimmers for all competition formats.",
    achievements: [
      "Won 12 national swimming championships",
      "ASCA Level 3 certified swim coach",
      "Former India national team swimmer in butterfly and IM events",
      "Coached swimmers to medals at the South Asian Games",
    ],
  },
  {
    slug: "jwala-gutta-badminton-delhi",
    name: "Jwala Gutta",
    avatar: "/images/coaches/jwala-gutta-badminton-delhi.svg",
    certifications: [
      { name: "BWF Coach Education Level 2", issuer: "BWF", year: 2019 },
    ],
    experienceYears: 10,
    sportsCoached: ["badminton"],
    specialization: ["doubles", "attacking play", "net kills"],
    location: {
      city: "Delhi",
      state: "Delhi",
      country: "IN",
      lat: 28.5650,
      lng: 77.1850,
    },
    contact: {
      phone: "+91 98 1101 5678",
      email: "jwala@badmintonhub.in",
    },
    verificationStatus: "verified",
    rating: { average: 4.6, count: 143 },
    status: "published",
    bio: "India's top doubles badminton specialist known for her aggressive net play and attacking style. Now coaching doubles pairs at the Badminton Hub in Delhi.",
    achievements: [
      "Won a bronze medal at the 2014 Asian Games in women's doubles",
      "Multiple-time national champion in women's doubles",
      "BWF Coach Education Level 2 certified",
      "Coached India's doubles pairs to multiple international medals",
    ],
  },
  {
    slug: "sandeep-sejwal-swimming-pune",
    name: "Sandeep Sejwal",
    avatar: "/images/coaches/sandeep-sejwal-swimming-pune.svg",
    certifications: [
      { name: "ASCA Level 2 Coach", issuer: "ASCA", year: 2018 },
    ],
    experienceYears: 11,
    sportsCoached: ["swimming"],
    specialization: ["breaststroke", "individual medley", "youth development"],
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "IN",
      lat: 18.5018,
      lng: 73.8050,
    },
    contact: {
      phone: "+91 98 2301 6789",
      email: "sandeep@puneswimming.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.5, count: 98 },
    status: "published",
    bio: "Former national champion swimmer and ASCA Level 2 certified coach specializing in breaststroke and individual medley. Focused on youth development and technique.",
    achievements: [
      "Won 8 national swimming titles in breaststroke",
      "ASCA Level 2 certified swimming coach",
      "Former India national team swimmer",
      "Coached 5 swimmers to national-level medals",
    ],
  },
  {
    slug: "krishna-prasad-cricket-madanapalle",
    name: "Krishna Prasad",
    avatar: "/images/coaches/krishna-prasad-cricket-madanapalle.svg",
    certifications: [
      { name: "BCCI Level 1 Coach", issuer: "BCCI", year: 2018 },
    ],
    experienceYears: 8,
    sportsCoached: ["cricket"],
    specialization: ["batting", "youth development", "fielding"],
    location: {
      city: "Madanapalle",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 13.5510,
      lng: 78.5010,
    },
    contact: {
      phone: "+91 98 4801 8901",
      email: "krishna@madanapalacricket.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.4, count: 42 },
    status: "published",
    bio: "BCCI Level 1 certified cricket coach developing young talent in Madanapalle, Chittoor district. Specializes in batting fundamentals and fielding drills for age-group cricketers.",
    achievements: [
      "BCCI Level 1 certified coach with 8 years of coaching experience",
      "Coached Madanapalle U-16 team to Chittoor district championship",
      "Developed a grassroots cricket program reaching 200+ young players",
      "Former Andhra Pradesh Ranji Trophy cricketer",
    ],
  },
  {
    slug: "priya-reddy-badminton-madanapalle",
    name: "Priya Reddy",
    avatar: "/images/coaches/priya-reddy-badminton-madanapalle.svg",
    certifications: [
      { name: "BWF Level 1 Coach", issuer: "Badminton World Federation", year: 2019 },
    ],
    experienceYears: 6,
    sportsCoached: ["badminton"],
    specialization: ["singles", "footwork", "junior development"],
    location: {
      city: "Madanapalle",
      state: "Andhra Pradesh",
      country: "IN",
      lat: 13.5510,
      lng: 78.5010,
    },
    contact: {
      phone: "+91 98 4801 9012",
      email: "priya@madanapallebadminton.com",
    },
    verificationStatus: "verified",
    rating: { average: 4.3, count: 35 },
    status: "published",
    bio: "BWF Level 1 certified badminton coach bringing professional training to Madanapalle. Specializes in junior singles development and footwork fundamentals.",
    achievements: [
      "BWF Level 1 certified badminton coach",
      "Coached 10+ players to Andhra Pradesh state-level competitions",
      "Founded the Madanapalle Badminton Development Program",
      "Former Andhra Pradesh state-level badminton champion",
    ],
  },
];

const coachToAcademySlug = {
  "rahul-dravid-cricket-bengaluru": "national-cricket-academy-bengaluru",
  "anil-kumble-spin-bengaluru": "national-cricket-academy-bengaluru",
  "ramesh-powar-cricket-bengaluru": "karnataka-institute-of-cricket-bengaluru",
  "venkatesh-prasad-cricket-bengaluru": "karnataka-institute-of-cricket-bengaluru",
  "jagadeesan-arun-cricket-bengaluru": "just-cricket-academy-bengaluru",
  "sunil-chhetri-football-bengaluru": "bengaluru-football-academy-bengaluru",
  "gurpreet-singh-sandhu-football-bengaluru": "bfc-soccer-schools-bengaluru",
  "prakash-padukone-badminton-bengaluru": "padukone-dravid-centre-sports-excellence-bengaluru",
  "mahesh-bhupathi-tennis-bengaluru": "kslta-tennis-academy-bengaluru",
  "akanksha-singh-basketball-bengaluru": "akanksha-singh-basketball-academy-bengaluru",
  "nisha-millet-swimming-bengaluru": "nisha-millet-swimming-academy-bengaluru",
  "virdhawal-khade-swimming-bengaluru": "bengaluru-swimming-academy-bengaluru",
  "saina-nehwal-badminton-hyderabad": "just-cricket-academy-bengaluru",
  "pankaj-advani-billiards-bengaluru": "akanksha-singh-basketball-academy-bengaluru",
  "pullela-gopichand-badminton-hyderabad": "pullela-gopichand-badminton-academy-hyderabad",
  "msk-prasad-cricket-hyderabad": "msk-prasad-cricket-academy-hyderabad",
  "sania-mirza-tennis-hyderabad": "leelage-tennis-academy-hyderabad",
  "vvs-laxman-cricket-hyderabad": "hca-cricket-academy-excellence-hyderabad",
  "saina-nehwal-badminton-hyderabad-2": "pullela-gopichand-badminton-academy-hyderabad",
  "amritpal-singh-basketball-hyderabad": "dunkit-basketball-academy-hyderabad",
  "ravi-shastri-cricket-chennai": "tamil-nadu-cricket-association-academy-chennai",
  "leander-paes-tennis-chennai": "sdat-tennis-stadium-chennai",
  "sachin-tendulkar-cricket-mumbai": "mumbai-cricket-association-academy-mumbai",
  "sunil-gavaskar-cricket-mumbai": "mumbai-cricket-association-academy-mumbai",
  "baichung-bhutia-football-mumbai": "football-school-of-india-mumbai",
  "michael-phelps-swimming-mumbai": "michael-phelps-swimming-mumbai",
  "rehan-poncha-swimming-mumbai": "sportiqo-swimming-mumbai",
  "kapil-dev-cricket-delhi": "ddca-cricket-academy-delhi",
  "sourav-ganguly-cricket-delhi": "ddca-cricket-academy-delhi",
  "gagan-narang-shooting-delhi": "pushsports-multi-sport-academy-delhi",
  "jwala-gutta-badminton-delhi": "badminton-hub-delhi",
  "dilip-vengsarkar-cricket-pune": "dilip-vengsarkar-cricket-academy-pune",
  "rahul-dravid-cricket-pune": "kshetram-cricket-academy-pune",
  "bhaichung-bhutia-football-pune": "asg-football-academy-pune",
  "saina-nehwal-badminton-pune": "badminton-academy-pune",
  "sandeep-sejwal-swimming-pune": "pune-swimming-academy-pune",
  "virender-sehwag-cricket-vijayawada": "vijayawada-cricket-academy-vijayawada",
  "sourav-ganguly-cricket-vijayawada": "andhra-cricket-academy-vijayawada",
  "baichung-bhutia-football-vijayawada": "vijayawada-football-academy-vijayawada",
  "saina-nehwal-badminton-vijayawada": "vijayawada-badminton-academy-vijayawada",
  "mahesh-bhupathi-tennis-vijayawada": "vijayawada-tennis-academy-vijayawada",
  "kapil-dev-cricket-visakhapatnam": "visakhapatnam-cricket-academy-visakhapatnam",
  "mahesh-bhupathi-tennis-visakhapatnam": "advance-tennis-academy-visakhapatnam",
  "saina-nehwal-badminton-visakhapatnam": "vizag-badminton-academy-visakhapatnam",
  "baichung-bhutia-football-visakhapatnam": "visakhapatnam-football-academy-visakhapatnam",
  "nisha-millet-swimming-visakhapatnam": "visakhapatnam-swimming-academy-visakhapatnam",
  "krishna-prasad-cricket-madanapalle": "madanapalle-cricket-academy-madanapalle",
  "priya-reddy-badminton-madanapalle": "madanapalle-badminton-academy-madanapalle",
};

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("Connected to MongoDB");

    const academies = await Academy.find({}, "slug").lean();
    const slugToId = {};
    for (const a of academies) {
      slugToId[a.slug] = a._id;
    }

    console.log("Deleting existing coaches...");
    await Coach.deleteMany({});

    const coachesToInsert = coaches.map((c) => {
      const academySlug = coachToAcademySlug[c.slug];
      if (academySlug && slugToId[academySlug]) {
        return { ...c, academyId: slugToId[academySlug] };
      }
      return c;
    });

    console.log(`Inserting ${coachesToInsert.length} coaches...`);
    await Coach.insertMany(coachesToInsert);

    console.log("Seeding complete!");
  } catch (err) {
    console.error("Seed error:", err);
  } finally {
    await mongoose.disconnect();
    console.log("Disconnected from MongoDB");
  }
}

seed();
