require("dns").setServers(["8.8.8.8", "8.8.4.4"]);
require("dotenv").config();
const mongoose = require('mongoose');
const Academy = require('../models/Academy');

const academies = [
  {
    slug: 'national-cricket-academy-bengaluru',
    name: 'National Cricket Academy',
    description: 'A premier cricket training institute with indoor nets, outdoor turf wickets, and a dedicated strength-conditioning block. Coaching follows BCCI age-group curricula with video-analysis support.',
    location: {
      address: 'M. Chinnaswamy Stadium, Cubbon Park',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'IN',
      lat: 12.9789,
      lng: 77.5996,
      pincode: '560001',
      geohash: 'td3',
    },
    contact: {
      phone: '+91 80 4012 9001',
      email: 'info@nationalcricketacademy.in',
      website: 'https://nationalcricketacademy.in',
    },
    sportsOffered: ['cricket'],
    facilities: ['indoor', 'outdoor', 'ground', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [
      { name: 'BCCI Level 1 Coach', issuer: 'BCCI', year: 2018 },
      { name: 'BCCI Level 2 Coach', issuer: 'BCCI', year: 2021 },
      { name: 'NSNIS Diploma in Sports Coaching', issuer: 'NSNIS Patiala', year: 2019 },
    ],
    verificationStatus: 'verified',
    achievementSignals: {
      stateAthletesProduced: 24,
      nationalAthletesProduced: 6,
      competitionParticipations: ['Ranji Trophy 2023–24', 'Syed Mushtaq Ali Trophy 2024', 'Vijay Hazare Trophy 2023', 'U-19 Cooch Behar Trophy 2023'],
      milestones: ['Hosted 2019 NCA Zonal Trials', 'Alumni include 2 Ranji captains', 'BCCI-certified Centre of Excellence'],
    },
    rating: { average: 4.7, count: 412 },
    coverImage: '/images/academies/national-cricket-academy-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'mumbai-football-academy-andheri',
    name: 'Mumbai Football Academy',
    description: 'AIFF-licensed residential academy focused on technical development for ages 8–18. Two full-size pitches, video-analysis room, and a sports science wing.',
    location: {
      address: 'Cooperage Football Ground, Nariman Point',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'IN',
      lat: 18.9265,
      lng: 72.8235,
      pincode: '400021',
      geohash: 'te7',
    },
    contact: {
      phone: '+91 22 2202 4008',
      email: 'contact@mfafootball.in',
      website: 'https://mfafootball.in',
    },
    sportsOffered: ['football'],
    facilities: ['outdoor', 'ground', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [
      { name: 'AIFF D License', issuer: 'AIFF', year: 2017 },
      { name: 'AFC C License', issuer: 'Asian Football Confederation', year: 2020 },
    ],
    verificationStatus: 'verified',
    achievementSignals: {
      stateAthletesProduced: 18,
      nationalAthletesProduced: 3,
      competitionParticipations: ['I-League 2nd Division 2023', 'Mumbai District Football Association League 2024', 'Subroto Cup 2023'],
      milestones: ['Top 10 finish in AIFF Elite Academy rankings 2022', 'Scouted by ISL clubs'],
    },
    rating: { average: 4.5, count: 286 },
    coverImage: '/images/academies/mumbai-football-academy-andheri.svg',
    status: 'published',
  },
  {
    slug: 'pullela-gopichand-badminton-academy-hyderabad',
    name: 'Pullela Gopichand Badminton Academy',
    description: 'Eight indoor wooden courts built to BWF standards, sports science lab, on-site physiotherapist, and structured pathway from sub-junior to elite.',
    location: {
      address: 'Gachibowli Indoor Stadium, Gachibowli',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'IN',
      lat: 17.4399,
      lng: 78.3569,
      pincode: '500032',
      geohash: 'tf1',
    },
    contact: {
      phone: '+91 40 2300 1850',
      email: 'academy@pgbadminton.in',
      website: 'https://pgbadminton.in',
    },
    sportsOffered: ['badminton'],
    facilities: ['indoor', 'court', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [
      { name: 'BWF Coach Education Level 1', issuer: 'Badminton World Federation', year: 2016 },
      { name: 'BWF Coach Education Level 2', issuer: 'Badminton World Federation', year: 2019 },
    ],
    verificationStatus: 'verified',
    achievementSignals: {
      stateAthletesProduced: 32,
      nationalAthletesProduced: 11,
      competitionParticipations: ['BWF World Tour 2024', 'Thomas Cup 2022', 'Uber Cup 2022', 'Senior Nationals 2024'],
      milestones: ['Produced Olympic medalists', 'Padma Bhushan recipient coaching staff', 'BWF High Performance Partner'],
    },
    rating: { average: 4.9, count: 538 },
    coverImage: '/images/academies/pullela-gopichand-badminton-academy-hyderabad.svg',
    status: 'published',
  },
  {
    slug: 'shiv-nadar-swimming-academy-chennai',
    name: 'Shiv Nadar Swimming Academy',
    description: 'Olympic-size heated pool, learn-to-swim to competitive squad pathway, and a dedicated age-group training programme following Swimming Federation of India guidelines.',
    location: {
      address: 'SDAT Aquatic Complex, Velachery',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'IN',
      lat: 12.9755,
      lng: 80.221,
      pincode: '600042',
      geohash: 'tf2',
    },
    contact: {
      phone: '+91 44 2253 2100',
      email: 'admin@shivnadarswim.in',
      website: 'https://shivnadarswim.in',
    },
    sportsOffered: ['swimming'],
    facilities: ['indoor', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [
      { name: 'AUSTSWIM Teacher of Swimming', issuer: 'AUSTSWIM', year: 2018 },
      { name: 'FINA Swimming Cert. Coach', issuer: 'World Aquatics', year: 2020 },
    ],
    verificationStatus: 'verified',
    achievementSignals: {
      stateAthletesProduced: 14,
      nationalAthletesProduced: 4,
      competitionParticipations: ['Senior National Aquatic Championship 2024', 'Khelo India Games 2023'],
      milestones: ['Two national record holders in age-group categories', 'Khelo India accredited centre'],
    },
    rating: { average: 4.6, count: 198 },
    coverImage: '/images/academies/shiv-nadar-swimming-academy-chennai.svg',
    status: 'published',
  },
  {
    slug: 'delhi-tennis-academy-rukmini-devi',
    name: 'Delhi Tennis Academy',
    description: 'AITA-recognised academy with five clay and three hard courts. Junior development pathway, wheelchair tennis, and performance squads led by ITF-certified coaches.',
    location: {
      address: 'R.K. Khanna Tennis Complex, Africa Avenue',
      city: 'New Delhi',
      state: 'Delhi',
      country: 'IN',
      lat: 28.5731,
      lng: 77.18,
      pincode: '110029',
      geohash: 'tt3',
    },
    contact: {
      phone: '+91 11 2617 6300',
      email: 'info@delhitennis.in',
      website: 'https://delhitennis.in',
    },
    sportsOffered: ['tennis'],
    facilities: ['outdoor', 'court', 'equipment', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [
      { name: 'ITF Level 1 Coach', issuer: 'International Tennis Federation', year: 2017 },
      { name: 'AITA Level 2 Coach', issuer: 'AITA', year: 2020 },
    ],
    verificationStatus: 'verified',
    achievementSignals: {
      stateAthletesProduced: 9,
      nationalAthletesProduced: 2,
      competitionParticipations: ['AITA National Championship 2024', 'ITF Junior Tour 2024'],
      milestones: ['ITF-recognised training centre', 'Hosted Davis Cup practice camp 2023'],
    },
    rating: { average: 4.4, count: 142 },
    coverImage: '/images/academies/delhi-tennis-academy-rukmini-devi.svg',
    status: 'published',
  },
  {
    slug: 'pro-kabaddi-academy-pune',
    name: 'Pro Kabaddi Academy Pune',
    description: 'Specialised kabaddi training on clay and synthetic mats, strength and raiding drills, and Pro Kabaddi League-aligned game preparation.',
    location: {
      address: 'Shree Shivchhatrapati Sports Complex, Balewadi',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'IN',
      lat: 18.5893,
      lng: 73.7857,
      pincode: '411045',
      geohash: 'te7',
    },
    contact: {
      phone: '+91 20 2734 5500',
      email: 'enroll@prokabaddi-pune.in',
      website: 'https://prokabaddi-pune.in',
    },
    sportsOffered: ['kabaddi'],
    facilities: ['outdoor', 'ground', 'equipment', 'gym', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [
      { name: 'AKFI National Coaching Cert.', issuer: 'Amateur Kabaddi Federation of India', year: 2019 },
    ],
    verificationStatus: 'pending',
    achievementSignals: {
      stateAthletesProduced: 11,
      nationalAthletesProduced: 1,
      competitionParticipations: ['Junior National Kabaddi 2023', 'Maharashtra State League 2024'],
      milestones: ['Two PKL players in current season squads'],
    },
    rating: { average: 4.3, count: 88 },
    coverImage: '/images/academies/pro-kabaddi-academy-pune.svg',
    status: 'published',
  },
  {
    slug: 'hockey-india-academy-ludhiana',
    name: 'Hockey India Academy',
    description: 'Astroturf pitches modelled on international standards, modern gym, recovery pools, and structured residential programme for ages 12–21.',
    location: {
      address: 'Punjab Agricultural University, Ground No. 4',
      city: 'Ludhiana',
      state: 'Punjab',
      country: 'IN',
      lat: 30.901,
      lng: 75.8573,
      pincode: '141004',
      geohash: 'tt8',
    },
    contact: {
      phone: '+91 161 2400 944',
      email: 'hockey@pau-edu.in',
      website: 'https://hockeyindia-academy.in',
    },
    sportsOffered: ['hockey'],
    facilities: ['outdoor', 'ground', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['intermediate', 'advanced', 'elite'],
    certifications: [
      { name: 'FIH Level 1 Coach', issuer: 'International Hockey Federation', year: 2018 },
      { name: 'FIH Level 2 Coach', issuer: 'International Hockey Federation', year: 2021 },
    ],
    verificationStatus: 'verified',
    achievementSignals: {
      stateAthletesProduced: 28,
      nationalAthletesProduced: 7,
      competitionParticipations: ['Hockey India League 2024', 'Junior Asia Cup 2023', 'Sub-Junior National Championship 2024'],
      milestones: ['Hockey India accredited High Performance Centre', 'Three Olympians coached in last 5 years'],
    },
    rating: { average: 4.7, count: 264 },
    coverImage: '/images/academies/hockey-india-academy-ludhiana.svg',
    status: 'published',
  },
  {
    slug: 'chess-gurukul-kolkata',
    name: 'Chess Gurukul',
    description: 'Dedicated chess training hall with tournament-standard clocks and boards. Group and 1:1 classes for beginners to FIDE-rated players.',
    location: {
      address: 'Salt Lake Stadium Complex, Sector 3',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'IN',
      lat: 22.5726,
      lng: 88.4173,
      pincode: '700106',
      geohash: 'tgc',
    },
    contact: {
      phone: '+91 33 2335 7000',
      email: 'learn@chessgurukul.in',
      website: 'https://chessgurukul.in',
    },
    sportsOffered: ['chess'],
    facilities: ['indoor', 'equipment', 'changing_room'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [
      { name: 'FIDE Trainer Title (FI)', issuer: 'FIDE', year: 2019 },
      { name: 'AICF National Arbiter', issuer: 'All India Chess Federation', year: 2020 },
    ],
    verificationStatus: 'verified',
    achievementSignals: {
      stateAthletesProduced: 7,
      nationalAthletesProduced: 1,
      competitionParticipations: ['National Chess Championship 2024', 'West Bengal State Open 2024'],
      milestones: ['Produced 1 GM and 4 IMs in last decade', 'AICF-affiliated training centre'],
    },
    rating: { average: 4.6, count: 96 },
    coverImage: '/images/academies/chess-gurukul-kolkata.svg',
    status: 'published',
  },
  {
    slug: 'tata-archery-academy-jamshedpur',
    name: 'Tata Archery Academy',
    description: 'A long-running residential archery programme with a 70m range, sports science lab, and structured pathway from state to national squad.',
    location: {
      address: 'Tatanagar, Bistupur',
      city: 'Jamshedpur',
      state: 'Jharkhand',
      country: 'IN',
      lat: 22.8046,
      lng: 86.2029,
      pincode: '831001',
      geohash: 'tgu',
    },
    contact: {
      phone: '+91 657 6641 100',
      email: 'archery@tatasteel.com',
      website: 'https://tata-archery.in',
    },
    sportsOffered: ['archery'],
    facilities: ['outdoor', 'ground', 'equipment', 'gym', 'changing_room', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [
      { name: 'World Archery Level 1 Coach', issuer: 'World Archery Federation', year: 2017 },
      { name: 'World Archery Level 2 Coach', issuer: 'World Archery Federation', year: 2021 },
    ],
    verificationStatus: 'verified',
    achievementSignals: {
      stateAthletesProduced: 19,
      nationalAthletesProduced: 5,
      competitionParticipations: ['World Archery Championships 2023', 'Asian Games 2022 (sending squad)'],
      milestones: ['Produced multiple Olympians since 2004', 'Padma Shri coaching staff'],
    },
    rating: { average: 4.8, count: 167 },
    coverImage: '/images/academies/tata-archery-academy-jamshedpur.svg',
    status: 'published',
  },
  {
    slug: 'yoga-and-gymnastics-tradition-bengaluru',
    name: 'Yoga & Gymnastics Tradition',
    description: 'Integrated yoga and artistic gymnastics centre with sprung floors, foam pits, and certified instructors for both disciplines under one roof.',
    location: {
      address: 'Koramangala Indoor Arena, 1st Block',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'IN',
      lat: 12.9352,
      lng: 77.6245,
      pincode: '560034',
      geohash: 'td3',
    },
    contact: {
      phone: '+91 80 4112 9080',
      email: 'hello@yogagymtradition.in',
      website: 'https://yogagymtradition.in',
    },
    sportsOffered: ['yoga', 'gymnastics'],
    facilities: ['indoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [
      { name: 'Yoga Alliance E-RYT 500', issuer: 'Yoga Alliance', year: 2018 },
      { name: 'FIG Brevet Coach Level 1', issuer: 'International Gymnastics Federation', year: 2020 },
    ],
    verificationStatus: 'verified',
    achievementSignals: {
      stateAthletesProduced: 5,
      nationalAthletesProduced: 1,
      competitionParticipations: ['Khelo India Youth Games 2023', 'National Gymnastics Championship 2024'],
      milestones: ['Produced a national rhythmic gymnastics medallist'],
    },
    rating: { average: 4.5, count: 121 },
    coverImage: '/images/academies/yoga-and-gymnastics-tradition-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'aikido-and-karate-tradition-imphal',
    name: 'Imphal Karate Dojo',
    description: 'Traditional karate and judo instruction in a structured dojo setting. Belt progression, kata and kumite coaching, and competition preparation.',
    location: {
      address: 'Khuman Lampak Sports Complex',
      city: 'Imphal',
      state: 'Manipur',
      country: 'IN',
      lat: 24.817,
      lng: 93.9368,
      pincode: '795001',
      geohash: 'wh6',
    },
    contact: {
      phone: '+91 385 2450 220',
      email: 'dojo@imphal-karate.in',
    },
    sportsOffered: ['karate'],
    facilities: ['indoor', 'equipment', 'changing_room'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [
      { name: 'JKI Instructor Cert.', issuer: 'Japan Karate International', year: 2018 },
      { name: 'Karate India Coach Cert.', issuer: 'Karate India Organisation', year: 2020 },
    ],
    verificationStatus: 'unverified',
    achievementSignals: {
      stateAthletesProduced: 4,
      nationalAthletesProduced: 0,
      competitionParticipations: ['North-East Karate Championship 2024'],
      milestones: ['Two state champions in 2023'],
    },
    rating: { average: 4.2, count: 41 },
    coverImage: '/images/academies/aikido-and-karate-tradition-imphal.svg',
    status: 'published',
  },
  {
    slug: 'skating-academy-ahmedabad',
    name: 'Ahmedabad Skating Academy',
    description: 'Indoor and outdoor skating rinks, inline and quad coaching, plus speed-skating and artistic-skating squads for ages 5+.',
    location: {
      address: 'Sabarmati Riverfront, Skating Rink 2',
      city: 'Ahmedabad',
      state: 'Gujarat',
      country: 'IN',
      lat: 23.0225,
      lng: 72.5714,
      pincode: '380009',
      geohash: 'tsj',
    },
    contact: {
      phone: '+91 79 2755 7700',
      email: 'enroll@ahmedabadskating.in',
      website: 'https://ahmedabadskating.in',
    },
    sportsOffered: ['skating'],
    facilities: ['outdoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [
      { name: 'Roller Skating Federation of India Cert.', issuer: 'RSFI', year: 2019 },
    ],
    verificationStatus: 'pending',
    achievementSignals: {
      stateAthletesProduced: 8,
      nationalAthletesProduced: 1,
      competitionParticipations: ['RSFI National Championship 2024', 'Khelo India Youth Games 2023'],
      milestones: ['Produced a national medal winner in inline speed skating'],
    },
    rating: { average: 4.3, count: 67 },
    coverImage: '/images/academies/skating-academy-ahmedabad.svg',
    status: 'published',
  },
];

async function seed() {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('Connected to MongoDB');

        await Academy.deleteMany({});
        console.log('Cleared existing academies');

        const result = await Academy.insertMany(academies);
        console.log(`Seeded ${result.length} academies`);

        await mongoose.disconnect();
        console.log('Done');
    } catch (err) {
        console.error('Seed failed:', err.message);
        process.exit(1);
    }
}

seed();
