require("dns").setServers(["8.8.8.8", "8.8.4.4"]);
require("dotenv").config();
const mongoose = require('mongoose');
const Academy = require('../models/Academy');

const academies = [
  // ── BENGALURU (10) ──────────────────────────────────────────────
  {
    slug: 'national-cricket-academy-bengaluru',
    name: 'National Cricket Academy (NCA)',
    description: "BCCI's apex cricket training facility housed at the M. Chinnaswamy Stadium campus. Features world-class indoor and outdoor nets, sports science labs, and rehabilitation centre.",
    location: { address: 'M. Chinnaswamy Stadium, Cubbon Park', city: 'Bengaluru', state: 'Karnataka', country: 'IN', lat: 12.9789, lng: 77.5996, pincode: '560001' },
    contact: { phone: '+91 80 4012 9001', email: 'nca@bcci.tv', website: 'https://www.bcci.tv' },
    sportsOffered: ['cricket'],
    facilities: ['indoor', 'outdoor', 'ground', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['advanced', 'elite'],
    certifications: [{ name: 'BCCI High Performance Centre', issuer: 'BCCI', year: 2007 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 28, nationalAthletesProduced: 12, competitionParticipations: ['Ranji Trophy selections', 'India U-19 program'], milestones: ["BCCI's premier cricket training centre", 'Alumni include multiple India captains'] },
    rating: { average: 4.8, count: 485 },
    coverImage: '/images/academies/national-cricket-academy-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'karnataka-institute-of-cricket-bengaluru',
    name: 'Karnataka Institute of Cricket (KIOC)',
    description: "One of South India's most respected private cricket academies located in Shivaji Nagar. Known for producing Ranji Trophy cricketers with structured coaching.",
    location: { address: '29, 7th Cross, Shivaji Nagar', city: 'Bengaluru', state: 'Karnataka', country: 'IN', lat: 12.9848, lng: 77.5850, pincode: '560001' },
    contact: { phone: '+91 80 2334 6789', email: 'info@kioc.in', website: 'https://kioc.in' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'BCCI Level 1 Coach', issuer: 'BCCI', year: 2015 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 18, nationalAthletesProduced: 3, competitionParticipations: ['Karnataka Premier League', 'Ranji Trophy squad selections'], milestones: ['Operating since 2003', 'Multiple KPL cricketers trained here'] },
    rating: { average: 4.5, count: 310 },
    coverImage: '/images/academies/karnataka-institute-of-cricket-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'just-cricket-academy-bengaluru',
    name: 'Just Cricket Academy',
    description: "Popular cricket academy in Yelahanka offering professional coaching with multiple turf and matting wickets. Well-regarded for junior development programs.",
    location: { address: 'Yelahanka New Town', city: 'Bengaluru', state: 'Karnataka', country: 'IN', lat: 13.1077, lng: 77.5726, pincode: '560064' },
    contact: { phone: '+91 98450 12345', email: 'info@justcricket.com', website: 'https://justcricket.com' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 8, nationalAthletesProduced: 1, competitionParticipations: ['Karnataka district-level tournaments'], milestones: ['10+ years in operation', '500+ students trained'] },
    rating: { average: 4.3, count: 245 },
    coverImage: '/images/academies/just-cricket-academy-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'bengaluru-football-academy-bengaluru',
    name: 'Bengaluru Football Academy (BFA)',
    description: "Premier residential football academy in Chikkagubbi with FIFA-standard artificial turf pitches, sports science wing, and structured pathway from grassroots to professional.",
    location: { address: 'Chikkagubbi Village, Jakkur', city: 'Bengaluru', state: 'Karnataka', country: 'IN', lat: 13.0720, lng: 77.5930, pincode: '560092' },
    contact: { phone: '+91 80 2845 6700', email: 'info@bfa.ac.in', website: 'https://bfa.ac.in' },
    sportsOffered: ['football'],
    facilities: ['outdoor', 'ground', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'AIFF D License', issuer: 'AIFF', year: 2019 }, { name: 'AFC C License', issuer: 'AFC', year: 2022 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 15, nationalAthletesProduced: 2, competitionParticipations: ['I-League 2nd Division', 'BDFA Super Division League'], milestones: ['Three players in national U-17 camp', 'AIFF Elite Academy ranking top 15'] },
    rating: { average: 4.4, count: 203 },
    coverImage: '/images/academies/bengaluru-football-academy-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'bfc-soccer-schools-bengaluru',
    name: 'BFC Soccer Schools',
    description: "Official youth development arm of Bengaluru FC. Grassroots and youth coaching centres across Bengaluru with AIFF-licensed coaches and structured player pathway.",
    location: { address: 'Sree Kanteerava Stadium, Bangalore Football Stadium', city: 'Bengaluru', state: 'Karnataka', country: 'IN', lat: 12.9615, lng: 77.5946, pincode: '560001' },
    contact: { phone: '+91 80 4211 0000', email: 'soccer.schools@bengalurufc.in', website: 'https://bfc.in/soccer-schools' },
    sportsOffered: ['football'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'AIFF D License', issuer: 'AIFF', year: 2020 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 20, nationalAthletesProduced: 4, competitionParticipations: ['Bengaluru FC youth leagues', 'AIFF Youth Leagues'], milestones: ['Backed by Bengaluru FC (ISL)', '1000+ youth enrolled'] },
    rating: { average: 4.6, count: 380 },
    coverImage: '/images/academies/bfc-soccer-schools-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'padukone-dravid-centre-sports-excellence-bengaluru',
    name: 'Padukone-Dravid Centre for Sports Excellence',
    description: "Multi-sport high-performance centre co-founded by Prakash Padukone and Rahul Dravid. World-class badminton, cricket, tennis, and basketball facilities on a 9-acre campus.",
    location: { address: 'Mallathahalli, Yelahanka', city: 'Bengaluru', state: 'Karnataka', country: 'IN', lat: 13.1050, lng: 77.5700, pincode: '560092' },
    contact: { phone: '+91 80 4680 4000', email: 'info@padukonedravid.com', website: 'https://padukonedravid.com' },
    sportsOffered: ['badminton', 'cricket', 'tennis', 'basketball'],
    facilities: ['indoor', 'outdoor', 'court', 'ground', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'BWF Coach Education', issuer: 'BWF', year: 2018 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 22, nationalAthletesProduced: 8, competitionParticipations: ['BWF World Tour', 'Olympic qualifiers'], milestones: ["Co-founded by Olympic medallist Prakash Padukone", "India's premier multi-sport academy"] },
    rating: { average: 4.9, count: 645 },
    coverImage: '/images/academies/padukone-dravid-centre-sports-excellence-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'kslta-tennis-academy-bengaluru',
    name: 'KSLTA Tennis Academy',
    description: "Karnataka State Lawn Tennis Association's academy at Cubbon Park. Multiple clay courts and hard courts with certified coaching staff. Hosts major ATP/WTA Challenger events.",
    location: { address: 'KSLTA Stadium, Cubbon Park', city: 'Bengaluru', state: 'Karnataka', country: 'IN', lat: 12.9776, lng: 77.5878, pincode: '560001' },
    contact: { phone: '+91 80 2224 4881', email: 'info@kslta.org', website: 'https://kslta.org' },
    sportsOffered: ['tennis'],
    facilities: ['outdoor', 'court', 'equipment', 'gym', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'AITA Certified Coach', issuer: 'AITA', year: 2017 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 22, nationalAthletesProduced: 5, competitionParticipations: ['ATP Challenger Bengaluru Open', 'AITA National Series'], milestones: ['Hosts ATP Challenger Bengaluru Open', '50+ years of tennis development'] },
    rating: { average: 4.5, count: 320 },
    coverImage: '/images/academies/kslta-tennis-academy-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'akanksha-singh-basketball-academy-bengaluru',
    name: 'Akanksha Singh Basketball Academy',
    description: "Professional basketball training academy at CSE campus, Betahalasuru. Co-founded by national team player Akanksha Singh, offering structured coaching from grassroots to competitive.",
    location: { address: 'CSE Campus, Betahalasuru', city: 'Bengaluru', state: 'Karnataka', country: 'IN', lat: 13.0950, lng: 77.5650, pincode: '560092' },
    contact: { phone: '+91 98450 56789', email: 'info@akankshabasketball.com', website: 'https://akankshabasketball.com' },
    sportsOffered: ['basketball'],
    facilities: ['indoor', 'court', 'equipment', 'gym', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 12, nationalAthletesProduced: 2, competitionParticipations: ['Karnataka State Basketball Championship', 'FBKI National Championship'], milestones: ['Founded by India women\'s basketball team player', '200+ students enrolled'] },
    rating: { average: 4.4, count: 175 },
    coverImage: '/images/academies/akanksha-singh-basketball-academy-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'nisha-millet-swimming-academy-bengaluru',
    name: 'Nisha Millet Swimming Academy',
    description: "Elite swimming academy founded by Olympian Nisha Millet. Olympic-size pool, expert coaching, and structured programs from learn-to-swim to competitive swim training.",
    location: { address: '2nd Floor, HAL 2nd Stage, Indiranagar', city: 'Bengaluru', state: 'Karnataka', country: 'IN', lat: 12.9784, lng: 77.6408, pincode: '560038' },
    contact: { phone: '+91 80 2528 4444', email: 'info@nishamilletswimming.com', website: 'https://nishamilletswimming.com' },
    sportsOffered: ['swimming'],
    facilities: ['indoor', 'outdoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 18, nationalAthletesProduced: 8, competitionParticipations: ['State Swimming Championships', 'National Aquatics Championship'], milestones: ['Founded by Olympian Nisha Millet', '2000+ students trained'] },
    rating: { average: 4.7, count: 435 },
    coverImage: '/images/academies/nisha-millet-swimming-academy-bengaluru.svg',
    status: 'published',
  },
  {
    slug: 'bengaluru-swimming-academy-bengaluru',
    name: 'Bengaluru Swimming Academy',
    description: "Established swimming academy with Olympic-size pool in central Bengaluru. Offers learn-to-swim programs, competitive training, and masters swimming for adults.",
    location: { address: 'Basavanagudi Swimming Pool Complex', city: 'Bengaluru', state: 'Karnataka', country: 'IN', lat: 12.9416, lng: 77.5790, pincode: '560004' },
    contact: { phone: '+91 80 2661 4545', email: 'contact@bengaluswimming.com' },
    sportsOffered: ['swimming'],
    facilities: ['outdoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 15, nationalAthletesProduced: 3, competitionParticipations: ['Karnataka State Aquatics', 'National Aquatics Championship'], milestones: ['15+ years in operation', 'Multiple state champions'] },
    rating: { average: 4.3, count: 210 },
    coverImage: '/images/academies/bengaluru-swimming-academy-bengaluru.svg',
    status: 'published',
  },

  // ── HYDERABAD (10) ──────────────────────────────────────────────
  {
    slug: 'pullela-gopichand-badminton-academy-hyderabad',
    name: 'Pullela Gopichand Badminton Academy',
    description: "World-renowned badminton academy founded by Pullela Gopichand. Eight BWF-standard indoor wooden courts, sports science lab, and on-site physiotherapy. Home to multiple Olympic and World Championship medalists.",
    location: { address: 'Gachibowli Indoor Stadium, Gachibowli', city: 'Hyderabad', state: 'Telangana', country: 'IN', lat: 17.4399, lng: 78.3569, pincode: '500032' },
    contact: { phone: '+91 40 2300 1850', email: 'academy@pgbadminton.in', website: 'https://pgbadminton.in' },
    sportsOffered: ['badminton'],
    facilities: ['indoor', 'court', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'BWF Coach Education Level 1', issuer: 'BWF', year: 2016 }, { name: 'BWF Coach Education Level 2', issuer: 'BWF', year: 2019 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 22, nationalAthletesProduced: 11, competitionParticipations: ['BWF World Tour', 'Thomas Cup 2022', 'Olympic Games'], milestones: ['Produced Olympic medalists', 'BWF High Performance Partner', 'Guru of Indian badminton'] },
    rating: { average: 4.9, count: 525 },
    coverImage: '/images/academies/pullela-gopichand-badminton-academy-hyderabad.svg',
    status: 'published',
  },
  {
    slug: 'hca-cricket-academy-excellence-hyderabad',
    name: 'HCA Cricket Academy of Excellence',
    description: "Hyderabad Cricket Association's high-performance academy at Secunderabad. Multiple turf wickets, indoor nets, gym, and video analysis.",
    location: { address: 'Sher-i-Kashmir Stadium, Secunderabad', city: 'Hyderabad', state: 'Telangana', country: 'IN', lat: 17.4400, lng: 78.5000, pincode: '500003' },
    contact: { phone: '+91 40 2780 1234', email: 'info@hyderabadoptics.in', website: 'https://hyderabadoptics.in' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'indoor', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'BCCI Affiliated Academy', issuer: 'BCCI', year: 2015 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 25, nationalAthletesProduced: 8, competitionParticipations: ['Ranji Trophy', 'IPL player pool', 'Vijay Hazare Trophy'], milestones: ["HCA's premier training facility", 'Multiple IPL players emerged'] },
    rating: { average: 4.6, count: 340 },
    coverImage: '/images/academies/hca-cricket-academy-excellence-hyderabad.svg',
    status: 'published',
  },
  {
    slug: 'msk-prasad-cricket-academy-hyderabad',
    name: 'MSK Prasad Cricket Academy',
    description: "Cricket academy founded by former Indian cricketer and chief selector MSK Prasad in Gachibowli. Professional coaching with focus on pace bowling and all-round development.",
    location: { address: 'Gachibowli', city: 'Hyderabad', state: 'Telangana', country: 'IN', lat: 17.4400, lng: 78.3489, pincode: '500032' },
    contact: { phone: '+91 98480 12345', email: 'info@mskprasadacademy.com' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'BCCI Level 1 Coach', issuer: 'BCCI', year: 2014 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 10, nationalAthletesProduced: 2, competitionParticipations: ['Hyderabad local leagues', 'HCA tournaments'], milestones: ['Founded by former India chief selector', 'Focus on pace bowling development'] },
    rating: { average: 4.3, count: 190 },
    coverImage: '/images/academies/msk-prasad-cricket-academy-hyderabad.svg',
    status: 'published',
  },
  {
    slug: 'dunkit-basketball-academy-hyderabad',
    name: 'Dunkit Basketball Academy',
    description: "Professional basketball academy in Gachibowli with indoor sprung-floor courts. Focus on youth development, shooting drills, and competitive league preparation.",
    location: { address: 'Gachibowli', city: 'Hyderabad', state: 'Telangana', country: 'IN', lat: 17.4350, lng: 78.3520, pincode: '500032' },
    contact: { phone: '+91 90000 67890', email: 'info@dunkit.in', website: 'https://dunkit.in' },
    sportsOffered: ['basketball'],
    facilities: ['indoor', 'court', 'equipment', 'gym', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 8, nationalAthletesProduced: 1, competitionParticipations: ['Telangana State Basketball Championship', 'FBKI National Championship'], milestones: ['Fastest-growing basketball academy in Hyderabad', 'Multiple state-level champions'] },
    rating: { average: 4.4, count: 160 },
    coverImage: '/images/academies/dunkit-basketball-academy-hyderabad.svg',
    status: 'published',
  },
  {
    slug: 'rising-star-basketball-academy-hyderabad',
    name: 'Rising Star Basketball Academy',
    description: "Community-driven basketball academy in the old city area. Focused on nurturing talent from underprivileged backgrounds with free coaching and equipment support.",
    location: { address: 'Tolichowki, Hyderabad', city: 'Hyderabad', state: 'Telangana', country: 'IN', lat: 17.3616, lng: 78.3950, pincode: '500008' },
    contact: { phone: '+91 98850 12345', email: 'info@risingstarba.com' },
    sportsOffered: ['basketball'],
    facilities: ['outdoor', 'court', 'equipment'],
    trainingLevels: ['beginner', 'intermediate'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 5, nationalAthletesProduced: 0, competitionParticipations: ['Telangana State Basketball League'], milestones: ['Free coaching for underprivileged youth', 'Social impact through sports'] },
    rating: { average: 4.2, count: 85 },
    coverImage: '/images/academies/rising-star-basketball-academy-hyderabad.svg',
    status: 'published',
  },
  {
    slug: 'hyderabad-football-club-academy-hyderabad',
    name: 'Hyderabad FC Academy',
    description: "Official youth academy of Hyderabad FC (ISL). Professional residential and day-scholar programs with FIFA-licensed coaching staff and modern training infrastructure.",
    location: { address: 'Gachibowli Stadium Complex', city: 'Hyderabad', state: 'Telangana', country: 'IN', lat: 17.4380, lng: 78.3580, pincode: '500032' },
    contact: { phone: '+91 40 4567 8900', email: 'academy@hyderabadfc.in', website: 'https://hyderabadfc.in' },
    sportsOffered: ['football'],
    facilities: ['outdoor', 'ground', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'AIFF D License', issuer: 'AIFF', year: 2020 }, { name: 'AFC C License', issuer: 'AFC', year: 2022 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 12, nationalAthletesProduced: 3, competitionParticipations: ['ISL Development League', 'AIFF Youth Leagues'], milestones: ['Backed by Hyderabad FC (ISL)', 'Residential football program'] },
    rating: { average: 4.5, count: 280 },
    coverImage: '/images/academies/hyderabad-football-club-academy-hyderabad.svg',
    status: 'published',
  },
  {
    slug: 'nsc-cricket-academy-hyderabad',
    name: 'NSC Cricket Academy',
    description: "Private cricket academy in Narsingi operated by former cricketer G. Lavan Patel. Professional coaching with multiple net sessions and match simulation.",
    location: { address: 'Narsingi, Near ORR', city: 'Hyderabad', state: 'Telangana', country: 'IN', lat: 17.3900, lng: 78.3200, pincode: '500089' },
    contact: { phone: '+91 98490 56789', email: 'info@nscacademy.com' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'BCCI Level 1 Coach', issuer: 'BCCI', year: 2018 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 8, nationalAthletesProduced: 1, competitionParticipations: ['HCA local tournaments'], milestones: ['Founded by ex-cricketer', 'Strong junior development program'] },
    rating: { average: 4.2, count: 140 },
    coverImage: '/images/academies/nsc-cricket-academy-hyderabad.svg',
    status: 'published',
  },
  {
    slug: 'leelage-tennis-academy-hyderabad',
    name: 'Leelage Tennis Academy',
    description: "Professional tennis coaching academy in Banjara Hills. Multiple courts with certified AITA coaches and junior development pathway programs.",
    location: { address: 'Banjara Hills', city: 'Hyderabad', state: 'Telangana', country: 'IN', lat: 17.4156, lng: 78.4347, pincode: '500034' },
    contact: { phone: '+91 98850 98765', email: 'info@leelagetennis.com' },
    sportsOffered: ['tennis'],
    facilities: ['outdoor', 'court', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'AITA Level 1 Coach', issuer: 'AITA', year: 2019 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 10, nationalAthletesProduced: 1, competitionParticipations: ['AITA National Series', 'Telangana State Tennis'], milestones: ['10+ years in operation', 'Multiple AITA tournament winners'] },
    rating: { average: 4.3, count: 165 },
    coverImage: '/images/academies/leelage-tennis-academy-hyderabad.svg',
    status: 'published',
  },
  {
    slug: 'gopuram-swimming-academy-hyderabad',
    name: 'Gopuram Swimming Academy',
    description: "Established swimming academy in Ameerpet with Olympic-size pool. Learn-to-swim and competitive training programs with certified swim coaches.",
    location: { address: 'Ameerpet, Hyderabad', city: 'Hyderabad', state: 'Telangana', country: 'IN', lat: 17.4374, lng: 78.4487, pincode: '500016' },
    contact: { phone: '+91 40 2375 1234', email: 'info@gopuramswimming.com' },
    sportsOffered: ['swimming'],
    facilities: ['outdoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 12, nationalAthletesProduced: 2, competitionParticipations: ['Telangana State Aquatics', 'National Aquatics Championship'], milestones: ['Olympic-size pool facility', '20+ years in operation'] },
    rating: { average: 4.3, count: 190 },
    coverImage: '/images/academies/gopuram-swimming-academy-hyderabad.svg',
    status: 'published',
  },
  {
    slug: 'dream-basketball-academy-hyderabad',
    name: 'Dream Basketball Academy',
    description: "Basketball coaching centre in Uppal focused on grassroots development. Outdoor and indoor courts with structured skill development programs.",
    location: { address: 'Uppal, Hyderabad', city: 'Hyderabad', state: 'Telangana', country: 'IN', lat: 17.4062, lng: 78.5510, pincode: '500039' },
    contact: { phone: '+91 90000 34567', email: 'info@dreamba.in' },
    sportsOffered: ['basketball'],
    facilities: ['outdoor', 'court', 'equipment', 'changing_room'],
    trainingLevels: ['beginner', 'intermediate'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 4, nationalAthletesProduced: 0, competitionParticipations: ['Telangana State Basketball Championship'], milestones: ['Grassroots basketball development', 'Affordable coaching fees'] },
    rating: { average: 4.1, count: 80 },
    coverImage: '/images/academies/dream-basketball-academy-hyderabad.svg',
    status: 'published',
  },

  // ── CHENNAI (8) ──────────────────────────────────────────────
  {
    slug: 'tamil-nadu-cricket-association-academy-chennai',
    name: 'TNCA Cricket Academy',
    description: "Tamil Nadu Cricket Association's official academy with world-class facilities. Multiple turf pitches, indoor nets, and sports science support.",
    location: { address: 'MAC Stadium, Chepauk', city: 'Chennai', state: 'Tamil Nadu', country: 'IN', lat: 13.0628, lng: 80.2790, pincode: '600002' },
    contact: { phone: '+91 44 2811 1234', email: 'info@tnca.in', website: 'https://tnca.in' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'indoor', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'BCCI Affiliated Academy', issuer: 'BCCI', year: 2010 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 18, nationalAthletesProduced: 10, competitionParticipations: ['Ranji Trophy', 'IPL player pool', 'Vijay Hazare Trophy'], milestones: ["TNCA's premier facility", 'Multiple Ranji-winning players trained here'] },
    rating: { average: 4.7, count: 405 },
    coverImage: '/images/academies/tamil-nadu-cricket-association-academy-chennai.svg',
    status: 'published',
  },
  {
    slug: 'sdat-tennis-stadium-chennai',
    name: 'SDAT Tennis Stadium',
    description: "Sports Development Authority of Tamil Nadu's tennis complex in Nungambakkam. Multiple clay and hard courts hosting national and international tournaments.",
    location: { address: 'Nungambakkam High Road', city: 'Chennai', state: 'Tamil Nadu', country: 'IN', lat: 13.0604, lng: 80.2496, pincode: '600034' },
    contact: { phone: '+91 44 2833 1234', email: 'info@sdat.tn.gov.in' },
    sportsOffered: ['tennis'],
    facilities: ['outdoor', 'court', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'AITA Certified', issuer: 'AITA', year: 2015 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 18, nationalAthletesProduced: 4, competitionParticipations: ['Chennai Open', 'AITA National Series'], milestones: ['Hosts Chennai Open (ATP)', '30+ years of tennis development'] },
    rating: { average: 4.4, count: 290 },
    coverImage: '/images/academies/sdat-tennis-stadium-chennai.svg',
    status: 'published',
  },
  {
    slug: 'fireball-badminton-academy-chennai',
    name: 'Fireball Badminton Academy',
    description: "Popular badminton academy in Velachery with multiple indoor courts. Professional coaching from former national players with structured junior and senior programs.",
    location: { address: 'Velachery, Chennai', city: 'Chennai', state: 'Tamil Nadu', country: 'IN', lat: 12.9815, lng: 80.2180, pincode: '600042' },
    contact: { phone: '+91 44 4211 5678', email: 'info@fireballbadminton.com', website: 'https://fireballbadminton.com' },
    sportsOffered: ['badminton'],
    facilities: ['indoor', 'court', 'equipment', 'gym', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 14, nationalAthletesProduced: 2, competitionParticipations: ['TN State Badminton Championship', 'All India Inter-State'], milestones: ['500+ active students', 'Multiple state champions produced'] },
    rating: { average: 4.5, count: 310 },
    coverImage: '/images/academies/fireball-badminton-academy-chennai.svg',
    status: 'published',
  },
  {
    slug: 'myndz-badminton-academy-chennai',
    name: 'Myndz Badminton Academy',
    description: "Modern badminton facility in OMR with professional-grade wooden courts. Coaching for all age groups with focus on technique and fitness.",
    location: { address: 'OMR Road, Thoraipakkam', city: 'Chennai', state: 'Tamil Nadu', country: 'IN', lat: 12.9450, lng: 80.2270, pincode: '600097' },
    contact: { phone: '+91 44 4201 9876', email: 'info@myndz.in', website: 'https://myndz.in' },
    sportsOffered: ['badminton'],
    facilities: ['indoor', 'court', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 6, nationalAthletesProduced: 0, competitionParticipations: ['Chennai District Badminton Tournament'], milestones: ['Modern facility on OMR corridor', 'Popular with IT professionals'] },
    rating: { average: 4.2, count: 180 },
    coverImage: '/images/academies/myndz-badminton-academy-chennai.svg',
    status: 'published',
  },
  {
    slug: 'chennai-football-academy-chennai',
    name: 'Chennai Football Academy',
    description: "AIFF-affiliated football academy in Chennai offering grassroots to professional training. Multiple turf grounds and licensed coaching staff.",
    location: { address: 'Jawaharlal Nehru Stadium Complex', city: 'Chennai', state: 'Tamil Nadu', country: 'IN', lat: 13.0107, lng: 80.2409, pincode: '600035' },
    contact: { phone: '+91 44 2230 1234', email: 'info@chennaifootball.in' },
    sportsOffered: ['football'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'AIFF D License', issuer: 'AIFF', year: 2018 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 10, nationalAthletesProduced: 1, competitionParticipations: ['I-League 2nd Division', 'TN State Football League'], milestones: ['AIFF-affiliated program', 'Residential training option'] },
    rating: { average: 4.2, count: 160 },
    coverImage: '/images/academies/chennai-football-academy-chennai.svg',
    status: 'published',
  },
  {
    slug: 'gopuram-basketball-academy-chennai',
    name: 'Gopuram Basketball Academy',
    description: "Basketball training academy in Anna Nagar with indoor courts. Focus on youth development and competitive preparation for state and national level tournaments.",
    location: { address: 'Anna Nagar, Chennai', city: 'Chennai', state: 'Tamil Nadu', country: 'IN', lat: 13.0850, lng: 80.2101, pincode: '600040' },
    contact: { phone: '+91 44 2620 4567', email: 'info@gopuramba.com' },
    sportsOffered: ['basketball'],
    facilities: ['indoor', 'court', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 8, nationalAthletesProduced: 1, competitionParticipations: ['TN State Basketball Championship', 'FBKI National Championship'], milestones: ['Leading basketball academy in Chennai', 'Multiple state medals'] },
    rating: { average: 4.3, count: 130 },
    coverImage: '/images/academies/gopuram-basketball-academy-chennai.svg',
    status: 'published',
  },
  {
    slug: 'chennai-swimming-academy-chennai',
    name: 'Chennai Swimming Academy',
    description: "Established swimming academy with Olympic-size pool in Adyar. Learn-to-swim, fitness swimming, and competitive training programs with certified coaches.",
    location: { address: 'Adyar, Chennai', city: 'Chennai', state: 'Tamil Nadu', country: 'IN', lat: 13.0063, lng: 80.2574, pincode: '600020' },
    contact: { phone: '+91 44 2441 1234', email: 'info@chennaiswimming.com' },
    sportsOffered: ['swimming'],
    facilities: ['outdoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 12, nationalAthletesProduced: 2, competitionParticipations: ['TN State Aquatics', 'National Aquatics Championship'], milestones: ['20+ years in operation', 'Multiple state records'] },
    rating: { average: 4.4, count: 220 },
    coverImage: '/images/academies/chennai-swimming-academy-chennai.svg',
    status: 'published',
  },
  {
    slug: 'cheetah-basketball-academy-chennai',
    name: 'Cheetah Basketball Academy',
    description: "Basketball training academy in Saidapet with outdoor courts. Affordable coaching for school and college students with tournament preparation.",
    location: { address: 'Saidapet, Chennai', city: 'Chennai', state: 'Tamil Nadu', country: 'IN', lat: 13.0215, lng: 80.2230, pincode: '600015' },
    contact: { phone: '+91 44 2432 5678', email: 'info@cheetahba.com' },
    sportsOffered: ['basketball'],
    facilities: ['outdoor', 'court', 'equipment'],
    trainingLevels: ['beginner', 'intermediate'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 3, nationalAthletesProduced: 0, competitionParticipations: ['Chennai District Basketball Tournament'], milestones: ['Affordable community basketball coaching'] },
    rating: { average: 4.0, count: 65 },
    coverImage: '/images/academies/cheetah-basketball-academy-chennai.svg',
    status: 'published',
  },

  // ── MUMBAI (7) ──────────────────────────────────────────────
  {
    slug: 'mumbai-cricket-association-academy-mumbai',
    name: 'Mumbai Cricket Association Academy',
    description: "MCA's premier cricket training facility. Multiple grounds with turf wickets, indoor nets, gym, and sports science support. Pipeline for Ranji Trophy and IPL.",
    location: { address: 'Wankhede Stadium, Churchgate', city: 'Mumbai', state: 'Maharashtra', country: 'IN', lat: 18.9388, lng: 72.8258, pincode: '400005' },
    contact: { phone: '+91 22 2281 1234', email: 'info@mumbaiindians.com', website: 'https://mca-cricket.com' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'indoor', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'BCCI Affiliated', issuer: 'BCCI', year: 2008 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 22, nationalAthletesProduced: 12, competitionParticipations: ['Ranji Trophy', 'IPL', 'Vijay Hazare Trophy'], milestones: ["MCA's premier facility", 'Multiple Ranji champions trained here'] },
    rating: { average: 4.8, count: 465 },
    coverImage: '/images/academies/mumbai-cricket-association-academy-mumbai.svg',
    status: 'published',
  },
  {
    slug: 'football-school-of-india-mumbai',
    name: 'Football School of India',
    description: "Professional football coaching academy in Andheri. FIFA-licensed coaches, artificial turf pitches, and structured pathway from grassroots to professional football.",
    location: { address: 'Andheri West, Mumbai', city: 'Mumbai', state: 'Maharashtra', country: 'IN', lat: 19.1364, lng: 72.8296, pincode: '400058' },
    contact: { phone: '+91 22 2670 1234', email: 'info@footballschoolofindia.com', website: 'https://footballschoolofindia.com' },
    sportsOffered: ['football'],
    facilities: ['outdoor', 'ground', 'equipment', 'gym', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'AIFF D License', issuer: 'AIFF', year: 2019 }, { name: 'AFC C License', issuer: 'AFC', year: 2022 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 12, nationalAthletesProduced: 2, competitionParticipations: ['I-League 2nd Division', 'Mumbai Football League'], milestones: ['FIFA-certified coaching', 'Residential program available'] },
    rating: { average: 4.5, count: 290 },
    coverImage: '/images/academies/football-school-of-india-mumbai.svg',
    status: 'published',
  },
  {
    slug: 'michael-phelps-swimming-mumbai',
    name: 'Michael Phelps Swimming',
    description: "World-renowned swimming academy chain's Mumbai franchise in Khar West. Olympic-standard coaching methodology with certified instructors.",
    location: { address: 'Sahar Plaza, Andheri-Khar Road, Khar West', city: 'Mumbai', state: 'Maharashtra', country: 'IN', lat: 19.1360, lng: 72.8420, pincode: '400052' },
    contact: { phone: '+91 22 4011 1234', email: 'info@michaelphelesswimming.in', website: 'https://michaelphelesswimming.in' },
    sportsOffered: ['swimming'],
    facilities: ['indoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'ASCA Certified', issuer: 'American Swimming Coaches Association', year: 2020 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 15, nationalAthletesProduced: 3, competitionParticipations: ['Mumbai District Aquatics', 'National Aquatics Championship'], milestones: ['Michael Phelps brand franchise', 'Olympic-level coaching methodology'] },
    rating: { average: 4.6, count: 350 },
    coverImage: '/images/academies/michael-phelps-swimming-mumbai.svg',
    status: 'published',
  },
  {
    slug: 'sportiqo-swimming-mumbai',
    name: 'Sportiqo Swimming Academy',
    description: "Modern swimming academy in Andheri with temperature-controlled pool. Learn-to-swim and lap swimming programs with experienced coaches.",
    location: { address: 'Andheri East, Mumbai', city: 'Mumbai', state: 'Maharashtra', country: 'IN', lat: 19.1136, lng: 72.8656, pincode: '400069' },
    contact: { phone: '+91 22 4015 5678', email: 'info@sportiqo.com', website: 'https://sportiqo.com' },
    sportsOffered: ['swimming'],
    facilities: ['indoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 6, nationalAthletesProduced: 0, competitionParticipations: ['Mumbai District Aquatics'], milestones: ['Temperature-controlled pool', 'Popular with corporate swimmers'] },
    rating: { average: 4.3, count: 200 },
    coverImage: '/images/academies/sportiqo-swimming-mumbai.svg',
    status: 'published',
  },
  {
    slug: 'mumbai-strikers-basketball-mumbai',
    name: 'Mumbai Strikers Basketball',
    description: "Basketball training program in Mumbai with indoor and outdoor courts. Youth development and competitive league preparation.",
    location: { address: 'BKC, Bandra East', city: 'Mumbai', state: 'Maharashtra', country: 'IN', lat: 19.0596, lng: 72.8656, pincode: '400051' },
    contact: { phone: '+91 22 4013 9876', email: 'info@mumbaistrikers.com' },
    sportsOffered: ['basketball'],
    facilities: ['indoor', 'court', 'equipment', 'changing_room'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 7, nationalAthletesProduced: 1, competitionParticipations: ['Maharashtra State Basketball Championship'], milestones: ['Growing basketball community in Mumbai', 'League-focused coaching'] },
    rating: { average: 4.2, count: 140 },
    coverImage: '/images/academies/mumbai-strikers-basketball-mumbai.svg',
    status: 'published',
  },
  {
    slug: 'vintage-football-club-mumbai',
    name: 'Vintage Football Club',
    description: "Established football academy in Dahisar West with full-size ground. Grassroots coaching and senior team competitive training.",
    location: { address: 'Dahisar West, Mumbai', city: 'Mumbai', state: 'Maharashtra', country: 'IN', lat: 19.2480, lng: 72.8560, pincode: '400068' },
    contact: { phone: '+91 22 2890 1234', email: 'info@vintagefc.in' },
    sportsOffered: ['football'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 8, nationalAthletesProduced: 0, competitionParticipations: ['Mumbai Football League', 'MDFA Elite Division'], milestones: ['20+ years of football development', 'Strong community presence'] },
    rating: { average: 4.1, count: 110 },
    coverImage: '/images/academies/vintage-football-club-mumbai.svg',
    status: 'published',
  },
  {
    slug: 'prabodhankar-thackerey-krida-mandal-mumbai',
    name: 'Prabodhankar Thackerey Krida Mandal',
    description: "Multi-sport complex in Thane with cricket, football, and badminton facilities. Community-driven sports development with affordable coaching.",
    location: { address: 'Thane West, Mumbai Metropolitan', city: 'Mumbai', state: 'Maharashtra', country: 'IN', lat: 19.2183, lng: 72.9781, pincode: '400601' },
    contact: { phone: '+91 22 2530 1234', email: 'info@ptkm.in' },
    sportsOffered: ['cricket', 'football', 'badminton'],
    facilities: ['outdoor', 'ground', 'indoor', 'court', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 10, nationalAthletesProduced: 0, competitionParticipations: ['Thane District tournaments'], milestones: ['Community sports development', '30+ years in operation'] },
    rating: { average: 4.2, count: 170 },
    coverImage: '/images/academies/prabodhankar-thackerey-krida-mandal-mumbai.svg',
    status: 'published',
  },

  // ── DELHI (5) ──────────────────────────────────────────────
  {
    slug: 'ddca-cricket-academy-delhi',
    name: 'DDCA Cricket Academy',
    description: "Delhi & District Cricket Association's cricket academy at Feroz Shah Kotla. Elite coaching with BCCI-certified staff and world-class facilities.",
    location: { address: 'Arun Jaitley Stadium, Feroz Shah Kotla', city: 'Delhi', state: 'Delhi', country: 'IN', lat: 28.6376, lng: 77.2430, pincode: '110002' },
    contact: { phone: '+91 11 2331 1234', email: 'info@ddca.in', website: 'https://ddca.in' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'indoor', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'BCCI Affiliated', issuer: 'BCCI', year: 2005 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 25, nationalAthletesProduced: 9, competitionParticipations: ['Ranji Trophy', 'IPL', 'Vijay Hazare Trophy'], milestones: ["India's most prolific Ranji team", 'Home of Delhi cricket'] },
    rating: { average: 4.8, count: 510 },
    coverImage: '/images/academies/ddca-cricket-academy-delhi.svg',
    status: 'published',
  },
  {
    slug: 'pushsports-multi-sport-academy-delhi',
    name: 'PushSports Multi-Sport Academy',
    description: "Multi-sport academy in Dwarka offering cricket, football, basketball, and badminton. Modern infrastructure with certified coaches for all age groups.",
    location: { address: 'Dwarka Sector 7, Delhi', city: 'Delhi', state: 'Delhi', country: 'IN', lat: 28.5800, lng: 77.0450, pincode: '110077' },
    contact: { phone: '+91 11 4567 1234', email: 'info@pushsports.in', website: 'https://pushsports.in' },
    sportsOffered: ['cricket', 'football', 'basketball', 'badminton'],
    facilities: ['indoor', 'outdoor', 'court', 'ground', 'equipment', 'gym', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 15, nationalAthletesProduced: 2, competitionParticipations: ['Delhi State tournaments', 'Dwarka District League'], milestones: ['Multi-sport development', '500+ active students'] },
    rating: { average: 4.4, count: 260 },
    coverImage: '/images/academies/pushsports-multi-sport-academy-delhi.svg',
    status: 'published',
  },
  {
    slug: 'badminton-hub-delhi',
    name: 'Badminton Hub Delhi',
    description: "Professional badminton academy with multiple indoor courts. Coaching from former national players with structured development pathway.",
    location: { address: 'R.K. Puram, Delhi', city: 'Delhi', state: 'Delhi', country: 'IN', lat: 28.5650, lng: 77.1850, pincode: '110022' },
    contact: { phone: '+91 11 2670 5678', email: 'info@badmintonhub.in' },
    sportsOffered: ['badminton'],
    facilities: ['indoor', 'court', 'equipment', 'gym', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 10, nationalAthletesProduced: 1, competitionParticipations: ['Delhi State Badminton Championship', 'All India Inter-State'], milestones: ['Leading badminton academy in South Delhi', 'Former national players as coaches'] },
    rating: { average: 4.3, count: 180 },
    coverImage: '/images/academies/badminton-hub-delhi.svg',
    status: 'published',
  },
  {
    slug: 'utsav-swimming-academy-delhi',
    name: 'Utsav Swimming Academy',
    description: "Swimming academy with Olympic-size pool in Dwarka. Learn-to-swim and competitive training programs with ASCA-certified coaches.",
    location: { address: 'Dwarka Sector 12, Delhi', city: 'Delhi', state: 'Delhi', country: 'IN', lat: 28.5850, lng: 77.0500, pincode: '110075' },
    contact: { phone: '+91 11 4560 9876', email: 'info@utsavswimming.com' },
    sportsOffered: ['swimming'],
    facilities: ['outdoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'ASCA Certified', issuer: 'ASCA', year: 2019 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 8, nationalAthletesProduced: 1, competitionParticipations: ['Delhi State Aquatics', 'National Aquatics Championship'], milestones: ['Olympic-size pool', 'Multiple state champions'] },
    rating: { average: 4.3, count: 190 },
    coverImage: '/images/academies/utsav-swimming-academy-delhi.svg',
    status: 'published',
  },
  {
    slug: 'delhi-basketball-academy-delhi',
    name: 'Delhi Basketball Academy',
    description: "Delhi's premier basketball academy with indoor sprung-floor courts. Youth development and senior competitive training programs.",
    location: { address: 'ITO, Delhi', city: 'Delhi', state: 'Delhi', country: 'IN', lat: 28.6280, lng: 77.2410, pincode: '110002' },
    contact: { phone: '+91 11 2332 1234', email: 'info@delhibasketball.in' },
    sportsOffered: ['basketball'],
    facilities: ['indoor', 'court', 'equipment', 'gym', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 10, nationalAthletesProduced: 2, competitionParticipations: ['Delhi State Basketball Championship', 'FBKI National Championship'], milestones: ["Delhi's oldest basketball academy", 'Multiple national players produced'] },
    rating: { average: 4.4, count: 210 },
    coverImage: '/images/academies/delhi-basketball-academy-delhi.svg',
    status: 'published',
  },

  // ── PUNE (5) ──────────────────────────────────────────────
  {
    slug: 'dilip-vengsarkar-cricket-academy-pune',
    name: 'Dilip Vengsarkar Cricket Academy',
    description: "Cricket academy founded by former Indian captain Dilip Vengsarkar in Kothrud. Professional coaching with BCCI-certified staff and emphasis on technique development.",
    location: { address: 'Kothrud, Pune', city: 'Pune', state: 'Maharashtra', country: 'IN', lat: 18.5074, lng: 73.8077, pincode: '411038' },
    contact: { phone: '+91 20 2546 1234', email: 'info@vengsarkaracademy.com' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'BCCI Level 1 Coach', issuer: 'BCCI', year: 2016 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 12, nationalAthletesProduced: 2, competitionParticipations: ['Maharashtra Premier League', 'Ranji Trophy selections'], milestones: ['Founded by former India captain', 'Strong technique-focused coaching'] },
    rating: { average: 4.4, count: 230 },
    coverImage: '/images/academies/dilip-vengsarkar-cricket-academy-pune.svg',
    status: 'published',
  },
  {
    slug: 'kshetram-cricket-academy-pune',
    name: 'Kshetram Sports Cricket Academy',
    description: "Cricket academy on Sinhagad Road with multiple practice nets and turf wickets. Structured coaching programs for school and college students.",
    location: { address: 'Sinhagad Road, Pune', city: 'Pune', state: 'Maharashtra', country: 'IN', lat: 18.4700, lng: 73.8300, pincode: '411030' },
    contact: { phone: '+91 20 2425 5678', email: 'info@kshetram.com' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 8, nationalAthletesProduced: 0, competitionParticipations: ['Pune District Cricket Tournament'], milestones: ['Popular with college students', 'Affordable coaching fees'] },
    rating: { average: 4.2, count: 150 },
    coverImage: '/images/academies/kshetram-cricket-academy-pune.svg',
    status: 'published',
  },
  {
    slug: 'asg-football-academy-pune',
    name: 'ASG Football Academy',
    description: "Professional football academy in Kharadi with FIFA-standard artificial turf. AIFF-licensed coaching and residential program for aspiring footballers.",
    location: { address: 'Kharadi, Pune', city: 'Pune', state: 'Maharashtra', country: 'IN', lat: 18.5530, lng: 73.9400, pincode: '411014' },
    contact: { phone: '+91 20 6710 1234', email: 'info@asgfootball.com' },
    sportsOffered: ['football'],
    facilities: ['outdoor', 'ground', 'equipment', 'gym', 'changing_room', 'parking', 'physio'],
    trainingLevels: ['beginner', 'intermediate', 'advanced', 'elite'],
    certifications: [{ name: 'AIFF D License', issuer: 'AIFF', year: 2020 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 10, nationalAthletesProduced: 1, competitionParticipations: ['I-League 2nd Division', 'Maharashtra State Football League'], milestones: ['FIFA-standard facility', 'Residential football program'] },
    rating: { average: 4.3, count: 180 },
    coverImage: '/images/academies/asg-football-academy-pune.svg',
    status: 'published',
  },
  {
    slug: 'badminton-academy-pune',
    name: 'Badminton Academy Pune',
    description: "Professional badminton coaching in Kothrud with multiple indoor wooden courts. Training for all levels from beginners to competitive players.",
    location: { address: 'Kothrud, Pune', city: 'Pune', state: 'Maharashtra', country: 'IN', lat: 18.5080, lng: 73.8085, pincode: '411038' },
    contact: { phone: '+91 20 2536 9876', email: 'info@badmintonpune.com' },
    sportsOffered: ['badminton'],
    facilities: ['indoor', 'court', 'equipment', 'gym', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 8, nationalAthletesProduced: 1, competitionParticipations: ['Maharashtra State Badminton Championship'], milestones: ['300+ active students', 'Multiple state-level players'] },
    rating: { average: 4.3, count: 195 },
    coverImage: '/images/academies/badminton-academy-pune.svg',
    status: 'published',
  },
  {
    slug: 'pune-swimming-academy-pune',
    name: 'Pune Swimming Academy',
    description: "Established swimming academy with Olympic-size pool in Kothrud. Learn-to-swim, fitness, and competitive programs with experienced coaches.",
    location: { address: 'Kothrud, Pune', city: 'Pune', state: 'Maharashtra', country: 'IN', lat: 18.5018, lng: 73.8050, pincode: '411038' },
    contact: { phone: '+91 20 2540 4567', email: 'info@puneswimming.com' },
    sportsOffered: ['swimming'],
    facilities: ['outdoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 10, nationalAthletesProduced: 1, competitionParticipations: ['Maharashtra State Aquatics', 'National Aquatics Championship'], milestones: ['15+ years in operation', 'Multiple state champions'] },
    rating: { average: 4.3, count: 200 },
    coverImage: '/images/academies/pune-swimming-academy-pune.svg',
    status: 'published',
  },

  // ── VIJAYAWADA (5) ──────────────────────────────────────────────
  {
    slug: 'vijayawada-cricket-academy-vijayawada',
    name: 'Vijayawada Cricket Academy',
    description: "Leading cricket academy in Vijayawada with turf wickets and professional coaching. Strong focus on developing talent for Andhra Pradesh Ranji team.",
    location: { address: 'Old Airport Road, Benz Circle', city: 'Vijayawada', state: 'Andhra Pradesh', country: 'IN', lat: 16.5062, lng: 80.6480, pincode: '520010' },
    contact: { phone: '+91 866 247 1234', email: 'info@vijayawadacricket.com' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'BCCI Level 1 Coach', issuer: 'BCCI', year: 2017 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 12, nationalAthletesProduced: 2, competitionParticipations: ['Andhra Pradesh Ranji Trophy', 'Vijay Hazare Trophy'], milestones: ['Top cricket academy in Krishna district', 'Multiple AP Ranji players'] },
    rating: { average: 4.4, count: 200 },
    coverImage: '/images/academies/vijayawada-cricket-academy-vijayawada.svg',
    status: 'published',
  },
  {
    slug: 'andhra-cricket-academy-vijayawada',
    name: 'Andhra Cricket Academy',
    description: "Established cricket coaching centre at Benz Circle with multiple practice nets. Produces talent for Andhra Pradesh state teams.",
    location: { address: 'Benz Circle, Vijayawada', city: 'Vijayawada', state: 'Andhra Pradesh', country: 'IN', lat: 16.5040, lng: 80.6350, pincode: '520010' },
    contact: { phone: '+91 866 257 5678', email: 'info@andhracricketacademy.com' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 8, nationalAthletesProduced: 0, competitionParticipations: ['Andhra Pradesh state tournaments'], milestones: ['15+ years in operation', 'Strong local reputation'] },
    rating: { average: 4.2, count: 130 },
    coverImage: '/images/academies/andhra-cricket-academy-vijayawada.svg',
    status: 'published',
  },
  {
    slug: 'vijayawada-football-academy-vijayawada',
    name: 'Vijayawada Football Academy',
    description: "Football coaching academy in Governorpet with full-size ground. Grassroots to competitive football development with licensed coaches.",
    location: { address: 'Governorpet, Vijayawada', city: 'Vijayawada', state: 'Andhra Pradesh', country: 'IN', lat: 16.5100, lng: 80.6200, pincode: '520002' },
    contact: { phone: '+91 866 245 9876', email: 'info@vijayawadafootball.com' },
    sportsOffered: ['football'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 6, nationalAthletesProduced: 0, competitionParticipations: ['AP State Football League'], milestones: ['Growing football culture in Vijayawada', '50+ active students'] },
    rating: { average: 4.1, count: 90 },
    coverImage: '/images/academies/vijayawada-football-academy-vijayawada.svg',
    status: 'published',
  },
  {
    slug: 'vijayawada-badminton-academy-vijayawada',
    name: 'Vijayawada Badminton Academy',
    description: "Indoor badminton facility with wooden courts and professional coaching. Training programs for all age groups and skill levels.",
    location: { address: 'Machavaram, Vijayawada', city: 'Vijayawada', state: 'Andhra Pradesh', country: 'IN', lat: 16.4900, lng: 80.6700, pincode: '520004' },
    contact: { phone: '+91 866 248 4567', email: 'info@vbadminton.com' },
    sportsOffered: ['badminton'],
    facilities: ['indoor', 'court', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 5, nationalAthletesProduced: 0, competitionParticipations: ['AP State Badminton Championship'], milestones: ['Modern indoor facility', 'Growing badminton community'] },
    rating: { average: 4.1, count: 100 },
    coverImage: '/images/academies/vijayawada-badminton-academy-vijayawada.svg',
    status: 'published',
  },
  {
    slug: 'vijayawada-tennis-academy-vijayawada',
    name: 'Vijayawada Tennis Academy',
    description: "Tennis coaching facility with clay and hard courts. Professional training for juniors and adults with AITA-certified coaches.",
    location: { address: 'Patamata, Vijayawada', city: 'Vijayawada', state: 'Andhra Pradesh', country: 'IN', lat: 16.5030, lng: 80.6400, pincode: '520010' },
    contact: { phone: '+91 866 249 8765', email: 'info@vijayawadatennis.com' },
    sportsOffered: ['tennis'],
    facilities: ['outdoor', 'court', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 4, nationalAthletesProduced: 0, competitionParticipations: ['AP State Tennis Championship'], milestones: ['Multi-court facility', 'Affordable tennis coaching'] },
    rating: { average: 4.0, count: 70 },
    coverImage: '/images/academies/vijayawada-tennis-academy-vijayawada.svg',
    status: 'published',
  },

  // ── VISAKHAPATNAM (5) ──────────────────────────────────────────────
  {
    slug: 'visakhapatnam-cricket-academy-visakhapatnam',
    name: 'Visakhapatnam Cricket Academy',
    description: "Leading cricket training facility in MVP Colony with turf wickets and indoor nets. Pipeline for Andhra Pradesh Ranji team selections.",
    location: { address: 'MVP Colony, Visakhapatnam', city: 'Visakhapatnam', state: 'Andhra Pradesh', country: 'IN', lat: 17.7215, lng: 83.3014, pincode: '530017' },
    contact: { phone: '+91 891 278 1234', email: 'info@vizagcricket.com' },
    sportsOffered: ['cricket'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [{ name: 'BCCI Level 1 Coach', issuer: 'BCCI', year: 2018 }],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 10, nationalAthletesProduced: 1, competitionParticipations: ['Andhra Pradesh Ranji Trophy', 'Vijay Hazare Trophy'], milestones: ['Top cricket academy in Vizag', 'Multiple AP Ranji players'] },
    rating: { average: 4.3, count: 180 },
    coverImage: '/images/academies/visakhapatnam-cricket-academy-visakhapatnam.svg',
    status: 'published',
  },
  {
    slug: 'advance-tennis-academy-visakhapatnam',
    name: 'Advance Tennis Academy',
    description: "Established tennis academy in Tpt Colony with multiple courts. Professional coaching for juniors and adults with focus on competitive play.",
    location: { address: 'Tpt Colony, Visakhapatnam', city: 'Visakhapatnam', state: 'Andhra Pradesh', country: 'IN', lat: 17.7100, lng: 83.3050, pincode: '530017' },
    contact: { phone: '+91 891 256 5678', email: 'info@advancetennis.in' },
    sportsOffered: ['tennis'],
    facilities: ['outdoor', 'court', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 6, nationalAthletesProduced: 0, competitionParticipations: ['AP State Tennis Championship', 'AITA National Series'], milestones: ['15+ years in operation', 'Multiple state-level champions'] },
    rating: { average: 4.2, count: 120 },
    coverImage: '/images/academies/advance-tennis-academy-visakhapatnam.svg',
    status: 'published',
  },
  {
    slug: 'vizag-badminton-academy-visakhapatnam',
    name: 'Vizag Badminton Academy',
    description: "Professional badminton coaching in the heart of Visakhapatnam. Indoor wooden courts with certified coaches for all skill levels.",
    location: { address: 'Dwaraka Nagar, Visakhapatnam', city: 'Visakhapatnam', state: 'Andhra Pradesh', country: 'IN', lat: 17.7250, lng: 83.2900, pincode: '530016' },
    contact: { phone: '+91 891 254 9876', email: 'info@vizagbadminton.com' },
    sportsOffered: ['badminton'],
    facilities: ['indoor', 'court', 'equipment', 'changing_room'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 5, nationalAthletesProduced: 0, competitionParticipations: ['AP State Badminton Championship'], milestones: ['Modern indoor facility', 'Growing popularity'] },
    rating: { average: 4.1, count: 95 },
    coverImage: '/images/academies/vizag-badminton-academy-visakhapatnam.svg',
    status: 'published',
  },
  {
    slug: 'visakhapatnam-football-academy-visakhapatnam',
    name: 'Visakhapatnam Football Academy',
    description: "Football coaching academy on Beach Road with full-size ground. Grassroots development and competitive training programs.",
    location: { address: 'Beach Road, Visakhapatnam', city: 'Visakhapatnam', state: 'Andhra Pradesh', country: 'IN', lat: 17.7160, lng: 83.3200, pincode: '530005' },
    contact: { phone: '+91 891 231 4567', email: 'info@vizagfootball.com' },
    sportsOffered: ['football'],
    facilities: ['outdoor', 'ground', 'equipment', 'changing_room'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 5, nationalAthletesProduced: 0, competitionParticipations: ['AP State Football League'], milestones: ['Beach Road facility', 'Growing football culture in Vizag'] },
    rating: { average: 4.0, count: 75 },
    coverImage: '/images/academies/visakhapatnam-football-academy-visakhapatnam.svg',
    status: 'published',
  },
  {
    slug: 'visakhapatnam-swimming-academy-visakhapatnam',
    name: 'Visakhapatnam Swimming Academy',
    description: "Swimming academy with Olympic-size pool in Rushikonda. Learn-to-swim and competitive training with certified coaches.",
    location: { address: 'Rushikonda, Visakhapatnam', city: 'Visakhapatnam', state: 'Andhra Pradesh', country: 'IN', lat: 17.7830, lng: 83.3780, pincode: '530045' },
    contact: { phone: '+91 891 279 8765', email: 'info@vizagswimming.com' },
    sportsOffered: ['swimming'],
    facilities: ['outdoor', 'equipment', 'changing_room', 'parking'],
    trainingLevels: ['beginner', 'intermediate', 'advanced'],
    certifications: [],
    verificationStatus: 'verified',
    achievementSignals: { stateAthletesProduced: 4, nationalAthletesProduced: 0, competitionParticipations: ['AP State Aquatics'], milestones: ['Scenic Rushikonda location', 'Popular with tourists and locals'] },
    rating: { average: 4.1, count: 85 },
    coverImage: '/images/academies/visakhapatnam-swimming-academy-visakhapatnam.svg',
    status: 'published',
  },
];

// ── Seed Script ───────────────────────────────────────────────────
async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('Connected to MongoDB');

    // Clear existing academies
    await Academy.deleteMany({});
    console.log('Cleared existing academies');

    // Insert new academies
    const result = await Academy.insertMany(academies);
    console.log(`Seeded ${result.length} academies successfully`);

    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
}

seed();
